### PR TITLE
Add itch.io service

### LINKED ISSUE #243: Itch.io service
http://itch.io/app

Does having an [Itch.io](http://itch.io/) runner for Lutris make sense? I don't see any available command line parsing in [the source](https://github.com/itchio/itch). We might have to add them.

### PR DESCRIPTION
**Pull request by GoGoOtaku**
This adds itch.io support - this took me a bit of work since I didn't find a full API documentation (open-api/swagger or just regular documentation) for itch.io. So I extracted the API from https://github.com/itchio/go-itchio.
**Just like the itch electron client this doesn't show games/apps bought in big bundles until they are manually added to the library (by clicking download on the bundle page)**
This is a limitation of itch.io. At this point I do not know how to even check which bundles the user owns and neither is there any indicator that a key is available through a previously purchased bundle through the game search function. I know this is awkward but I can't really do anything against this atm and itch.io has stated repeatedly that they do not want this to work differently.

I also added the ability to give the Downloader cookies since I needed cookies for authentication. Unless I did something wrong.

### TODO
- [x] Download and install patches
- [x] Download assets (if separate)
- [x] Download extras
- [x] Handle multiple files
- [x] ~~Handle Flash, HTML, etc. based games (currently just Linux and Wine) (optional)~~
- [x] ~~Uploading play time to itch.io servers (optional)~~
- [x] Probably more stuff I forgor...
- [x] Code Cleanup

Things that ARE implemented:
- Get library of purchased games
- Install Linux and Windows games
- Install (free) games with lutris installer script
- Update games
- Install extras like manual, soundtrack, art, etc...

Things that are NOT implemented:
- "embedded" games for the browser (HTML, Unity, Flash, Java) - Playable through the itch.io website
- "Offline" games like RPG manuals, printable card games, etc (mostly just a PDF anyway)
- Wharf Patching (I am very sorry itch.io :cry:)
- Collections

Things that are not implemented for external reasons:
- DLC support - itch.io doesn't have any facilities for DLC. So games and DLC can not automatically linked. There are only a handful of "DLC" on itch that have to be manually installed anyway. We COULD implement a list of known DLC which would be manually kept up to date. There is a DLC tag on itch.io (tags can not be queried over the API as far as I can tell)
- Bundle games - Like mentioned above. This is a thing with itch. To add games to the library the "Download" button on the bundle page has to be clicked which leads to a page with download links and installation instructions. This will _activate_ the game. The game does not need to be actually downloaded.

This will close #243

### CODE REVIEW

**Comment by GoGoOtaku** [comment]
### Tested Games:

<details><summary>Celeste :heavy_check_mark:</summary>

Runner: Linux
Issues: _None_
**Status: Works**
</details>
<details><summary>Gun Gods :heavy_check_mark:</summary>

Runner: Wine
Issues: Requires virtual screen (prevents camera spinning) and forced mouse capture
Fault: Game
**Status: Works**
</details>
<details><summary>Lenna's Inception</summary>

Runner: Linux
Issues: Crash on Launch
Fault: Game/Xrandr
**Status: Installed**
</details>
<details><summary>MewnBase :heavy_check_mark:</summary>

Runner: Linux
Issues: _None_
**Status: Works**
</details>
<details><summary>Micro Mages PC/NES :x:</summary>

Runner: Wine
Issues: Installer extracts installer instead of executing
Fault: lutris
Workaround: external script [untested]
**Status: Fails**
</details>
<details><summary>Minit</summary>

Runner: Linux
Issues: Crash on Launch
Fault: Game/YoYo
Workaround: external script with wine runner [untested]
**Status: Installed**
</details>
<details><summary>Nuclear Throne</summary>

Runner: Linux
Issues: Crash on Launch
Fault: Game/YoYo
Workaround: external script with wine runner [untested]
**Status: Installed**
</details>
<details><summary>Pixel Fireplace :heavy_check_mark:</summary>

Runner: Linux
Issues: _None_
**Status: Works**
</details>
<details><summary>//nullpointer :heavy_check_mark:</summary>

Runner: Linux
Issues: _None_
**Status: Works**
</details>

**Comment by GoGoOtaku** [comment]
Open for review!
Hope this helps some people.

Wharf patching is something that I will look at at a later date but is something that we should definitely add in the long run. I looked into if it is easy but it is more complex and I rather finish one thing first.
(Wharf patching is a diff based game updates which reduces the load of itch.io servers during updates)

**Comment by GoGoOtaku** [comment]
PS: I added my HoloCure script to lutris.net if people are interested in that

**Comment by strycore** [comment]
Woohoo! I'm excited to finally test Itch.io integration in Lutris!

**Comment by 5310** [comment]
To confirm, the Itch source isn't in version 0.5.12, right, the FlatHub version? 

I was really excited to check out some Itch games on my Deck and couldn't find it in the sources 🥲

**Comment by danieljohnson2** [comment]
That's right. The next release should have it, but I don't know when that's going to be.

**Pull request merged**
