### PR TITLE
Accept both PNG and JPEG files as custom banners or cover art, without transcoding

### LINKED ISSUE #5149: Cover and banner art has no transparency.
### Bug description

Cover and banner art has no transparency when using a PNG image. Same image works just fine as an icon. Not sure if this is a bug or just not currently supported.

image

### How to Reproduce

Go to "Game Info" tab of the "Configuration", add PNG image with transparency to cover, banner and icon. Icon is only one showing transparency.

### Expected behavior

Transparency to be visible in cover, banner art just like icon when using a PNG image.

### Log output

```shell
INFO     2023-11-27 23:48:32,416 [application.do_command_line:436]:Starting Lutris 0.5.14
INFO     2023-11-27 23:48:32,418 [startup.get_drivers:70]:Running AMD Mesa driver 23.2.1 on AMD Radeon RX 6600 (navi23, LLVM 15.0.7, DRM 3.54, 6.5.0-13-generic) (0x73ff)
INFO     2023-11-27 23:48:32,419 [display.display_gpu_info:78]:GPU: 1002:73FF 1458:2334 (amdgpu drivers)
it looks like wine32 is missing, you should install it.
as root, please execute "apt-get install wine32:i386"
DEBUG    2023-11-27 23:48:33,434 [lutris.get_missing_game_ids:202]:Checking for missing games
DEBUG    2023-11-27 23:49:23,965 [application.show_window:359]:Showing window EditGameConfigDialog20
DEBUG    2023-11-27 23:49:45,105 [game.save:429]:Saving Empire Earth (wine) with config ID empire-earth-1700852079
DEBUG    2023-11-27 23:49:45,106 [config.save:227]:Saving LutrisConfig(level=game, game_config_id=empire-earth-1700852079, runner=wine) config to /home/david/.config/lutris/games/empire-earth-1700852079.yml
DEBUG    2023-11-27 23:49:46,110 [lutris.add_to_path_cache:160]:Adding Empire Earth (wine) to path cache
DEBUG    2023-11-27 23:49:46,157 [application.on_app_window_destroyed:377]:Removed window EditGameConfigDialog20
```

### System Information

```shell
[System]
OS:              Ubuntu 23.10 Mantic Minotaur
Arch:            x86_64
Kernel:          6.5.0-13-generic
Desktop:         ubuntu:GNOME
Display Server:  wayland

[CPU]
Vendor:          GenuineIntel
Model:           Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz
Physical cores:  16
Logical cores:   32

[Memory]
RAM:             62.6 GB
Swap:            8.0 GB

[Graphics]
Vendor:          AMD
OpenGL Renderer: AMD Radeon RX 6600 (navi23, LLVM 15.0.7, DRM 3.54, 6.5.0-13-generic)
OpenGL Version:  4.6 (Compatibility Profile) Mesa 23.2.1-1ubuntu3
OpenGL Core:     4.6 (Core Profile) Mesa 23.2.1-1ubuntu3
OpenGL ES:       OpenGL ES 3.2 Mesa 23.2.1-1ubuntu3
Vulkan Version:  1.3.250
Vulkan Drivers:  AMD Radeon RX 6600 (RADV NAVI23) (1.3.255)
```

### Media (optional)

_No response_

### PR DESCRIPTION
**Pull request by danieljohnson2**
Lutris uses JPEG files for banners and cover art, and that's what we provide- but user can select their own media. We currently transcode anything we get to JPEG, which is lossy and which does not support transparency. So lets fix that.

Screenshot from 2023-12-31 09-00-45

This PR gives Lutris cover-art and banners *two* file types, JPEG and PNG. If you use either as your custom file format, we just copy that file in. We use the right file extension depending on the type, so this means Lutris needs to look for two different files. This should not slow us down much since we check for JPEG first, and we should normally find it and stop looking.

As a bonus, this PR also switches the custom cover art select (and the refresh button) to use the trash, so your previously installed art is not lost.

The transcoding process might fail, so we now transcode to a temp file before trashing anything, then just rename the temp file afterwards.

Only Lutris media are doubled in this way; the others are not customizable, so we need not change them.

Lutris icons are still PNG only, since we seem to be trying to get GNOME to understand them.

Resolves #5149

### CODE REVIEW

**Comment by strycore** [comment]
I'll probably regret merging this down the road but there's goes nothing!!

**Comment by danieljohnson2** [comment]
I'm surprised you preferred this ~~bug collection~~pull request over #5314, really. You seemed more interested in that one.

**Comment by strycore** [comment]
> You seemed more interested in that one.

I am, but it still needs rebasing.

**Comment by danieljohnson2** [comment]
Whoops, I overlooked that (again); my PRs conflicted with each other.

I've rebased it now.

**Pull request merged**
