### PR TITLE
Add wine version choice to the installer

### PR DESCRIPTION
**Pull request by sigmaSd**
screenshot from 2018-11-01 13-23-01

### CODE REVIEW

**Comment by sigmaSd** [comment]
fix https://github.com/lutris/lutris/issues/1014

**Comment by tannisroot** [comment]
I think “installer-specified wine” is more obvious and sounds better. Should probably have something like “Recommend” near it too.
Also, “Use” before each option doesn’t look very good, users can get confused.
Can it be like this?
Use:
- installer-specified wine
- default wine
- system wine

Also, would it be possible to show what wine version is behind each option? 
Would look kind of like this:
- installer-specified wine (tkg-3.19-86_64) - Recommenced (in bold)

**Comment by sigmaSd** [comment]
1 - I changed the names to what you suggested.
2 - who gets to decide whats recommended , even if the install script specifies it it will just get outdated with time
3 - version added
screenshot from 2018-11-01 14-03-31

**Comment by PythonicChemist** [comment]
Maybe write something like "Select Wine version:" before listing the options, then call the options simply recommended, default, system? Also It would be great to standardize the wine version format. It does look kind of messy right now.

**Comment by sigmaSd** [comment]
making the installer provided one recommended feels weird cause scripts gets outdated quickly,
I prefer not to add "select wine" cause i'll have to account for the case where only one version exist and remove that label, 
I agree it looks messy what about adding version to tooltip instead?

**Comment by PythonicChemist** [comment]
If only one version exists, this feature should be invisible to the user anyways imo.

**Comment by sigmaSd** [comment]
I believe the case where only one version exists is rare plus even with one choice it doesn't look bad visually

**Comment by sigmaSd** [comment]
screenshot from 2018-11-01 15-14-47

Cool info to be able to screenshot the tooltip you can't use the screenshot window option you have to screenshot all the desktop

**Comment by sigmaSd** [comment]
@PythonicChemist added ur ideas :) this feature will be invisible if there is only one version
screenshot from 2018-11-01 15-33-49

**Comment by sigmaSd** [comment]
winesteam
screenshot from 2018-11-01 15-41-40

**Comment by tannisroot** [comment]
Why is Winesteam one different? You can use custom wine versions with those and custom prefixes too.

**Comment by tannisroot** [comment]
I would prefer if it had some sort of indication that installer-specific wine is recommended as usually that’s the version the game was tested with and confirmed working. It’s rare for a game to just stop working with the same wine version after a while, the installers are usually made broken or vandalized.

**Comment by sigmaSd** [comment]
winesteam has the same logic, its just that the install script for that game "advance quest" is that simple
make sense, so would installer-specified (Recommended) be enough?

**Comment by sigmaSd** [comment]
screenshot from 2018-11-01 16-49-18
I like it, it works well with the tooltip

**Comment by strycore** [comment]
This actually offering users to break their games by letting them use another wine version that what is used in the installer. This is a feature that can only be used for doing bad and ugly things, I don't see how can this possibly make the lifes of the users better when we give such ways to harm them.

**Comment by sigmaSd** [comment]
I see your point, will close I guess, I'll reopen if someone have a good argument for it.

**Comment by tannisroot** [comment]
I have 3 arguments for this option:
1) I have no idea why, bu the servers Lutris hosts wine are complete crap and have abysmally slow speed, at least for people from Europe. So I would rather use whatever wine version I have that i know will work just fine with the game I am downloading than to wait half an hour for Lutris to finish downloading Wine and then doing that again 3 more times because it broze after it has downloaded it.
2) Save time/money for people with bad or limited internet connection
3) Avoid downloading ancient version of wine because the installer wasn’t updated in ages. I will switch to something newer after the installation anyway, so why waste time?
If users breaking stuff is such a big concern, the option can hidden under a spoiler of some sort.
So yeah, please reopen, this is a good PR.

**Comment by strycore** [comment]
This is not a proper solution to the problem you are exposing, it cannot get solved by butchering the UI and entrapping users.

**Comment by tannisroot** [comment]
At the end of the day, what should we care about more - the UI or usability of the scripts?

**Comment by sigmaSd** [comment]
I definitely sympathize with tannisroot points , those are actually also my personal reasons for doing this pr, but also I agree with strycore this pr doesn't fit with the lutris philosophy of making installing games on linux as easy as hitting the install button without much thinking.
That being said I think pr likes this will still pop in the future where something must be sacrificed usability or friendliness, so what I suggest is hiding this pr with `LUTRIS_ADVANCED` env and future pr like this

**Comment by AlexanderRavenheart** [comment]
Hiding features behind environment variables is basically invalidating the feature for all but the most technical and curious of users. Environment variables should not be used for user facing options, but for changing features in a development environment.

**Comment by tannisroot** [comment]
So why add this feature to the milestone then? This all just a waste of code and time now.

**Pull request closed without merging**
