### PR TITLE
Skip downloading cached files

### PR DESCRIPTION
**Pull request by DanBmh**
Adds a check if an installation file is already existing in the cache and skips downloading it then.

My problem was that the download failed midways and I could not resume it anymore. I always needed to restart the complete download, wait until it retrieved all the already existing files, only to find out that it failed again after some hours. So this was wasting time and energy/bandwidth...

Note that the current approach might cause problems if a cached file is broken/incomplete because it is skipped as well.
This can happen for example if Lutris is started from the command line and the download is aborted by canceling the program directly (if the download is aborted via the GUI, the intermediate file is deleted correctly).

### CODE REVIEW

**Comment by DanBmh** [comment]
This should also help with the installation problems in https://github.com/lutris/lutris/issues/5611, https://github.com/lutris/lutris/issues/5599. \
It doesn't fix the error, but allows to restart the download, without having to re-download everything again. \
I had it as well, and around after the same time again on my second try, so maybe its some timeout problem.

**Comment by BileDemon** [comment]
This is great! Thanks for implementing this feature.
I hope it gets merged before the next milestone release.

**Comment by danieljohnson2** [comment]
You seem to have accidentally added some unrelated commits that update readme files. Maybe those should be in another PR.

I am also concerned about robustness in the face of a crash- a half downloaded file would not be re-downloaded, so if we fail to delete it (and we would in a crash) we'd wind up unable to install that game afterwards.

I think we need a way to recognize incomplete files; say, we could download to a temp file and then rename on completion- something like that.

**Comment by DanBmh** [comment]
> I think we need a way to recognize incomplete files; say, we could download to a temp file and then rename on completion- something like that.

Good idea, I've updated it.

**Comment by danieljohnson2** [comment]
Better, but I do not feel good using a fixed name ('download.tmp') for this- if we do parallel downloads this will fail.

The ``tempfile`` module seems awfully awkward though. How about we just take ``file.dest_file`` and pop a suffix on the end? That is simple, and it lets you see what the temp file will become when it grows up.

It can still fail if somehow we wind up downloading the same file twice at the same time, but I don't think that's going to work out too well anyway.

**Comment by danieljohnson2** [comment]
I've tested this and it seems to work; I think we can merge this.

I may be asking for a paddlin' from @strycore, but I think I will merge this as a 'fix' for #5611 and #5599.

**Comment by DanBmh** [comment]
> I may be asking for a paddlin' from @strycore, but I think I will merge this as a 'fix' for https://github.com/lutris/lutris/issues/5611 and https://github.com/lutris/lutris/issues/5599.

I think a 'solution' for those could be to reauthenticate or regenerate the download links before each new file. Since I only needed to restart the download, I don't think the problem is within lutris, but rather that the links/downloads are only valid for a certain amount of time (I normally was able to download about 4 files (~18gb, 1h) before it failed).

**Pull request merged**
