### PR TITLE
Add Platform icons

### PR DESCRIPTION
**Pull request by RobLoach**
This adds support for Platforms to have icons in the sidebar.

platform_icons

### CODE REVIEW

**Comment by TingPing** [comment]
Ideally these would be symbolic SVGs.

**Comment by RobLoach** [comment]
> Ideally these would be symbolic SVGs.

Oh definitely. Let's tackle that over in your other issue https://github.com/lutris/lutris/issues/582 :+1:

**Comment by strycore** [comment]
@RobLoach can you add a spacer or a blank icon for the platforms that don't provide icons? I'll merge your PR after.

**Comment by RobLoach** [comment]
That looks better. Good call.

screenshot at 2017-06-23 16-21-31

**Pull request merged**
