### PR TITLE
update copyright years

### PR DESCRIPTION
**Pull request by fschaupp**

### CODE REVIEW

**Comment by danieljohnson2** [comment]
Say, this changes the text 'video game preservation platform' in .desktop file to "Open gaming platform".

The "preservation platform" language is a bit unclear to me, but if we're changing it, shouldn't it change in all the places that use it?

This PR also adds stuff about Patreon to the README, but I suppose it was an oversight that it was missing anyway.

**Comment by fschaupp** [comment]
@danieljohnson2 Thanks for the hint. Didn't see the other commits also being referenced to the pull request.
I branched the changes off and created a new pull request so the other changes not being mixed into the PR. 
See [#4253](https://github.com/lutris/lutris/pull/4253)

**Comment by strycore** [comment]
Please keep "'video game preservation platform", I'm not interested in working on an open gaming platform.

**Comment by fschaupp** [comment]
> Please keep "'video game preservation platform", I'm not interested in working on an open gaming platform.

It seems like I accidentally merged the texts from the (deprecated?) dev-branch into my master branch.

**Pull request closed without merging**
