### PR TITLE
Update desktop icons after copy.

### LINKED ISSUE #659: Shortcut icons not updated when changing icons in Lutris
If you configure a game and change its icon to a custom one within Lutris, that icon does not seem to be used when creating a desktop shortcut. Instead the default icon off the website gets used.

Is this expected behavior or a bug?

### PR DESCRIPTION
**Pull request by Xenega**
Force update of icon cache with xdg-icon-resource. I execute "xdg-icon-resource forceupdate" after each copy of a icon. I think xdg-icon-resource is sufficient cross-unix, but surprise can happen.

Fix #659

### CODE REVIEW

**Comment by strycore** [comment]
Looks cool

**Comment by TingPing** [comment]
Instead of introducing an intermediate dependency you should just call `gtk-update-icon-cache`, this tool adds no value on top.

**Comment by strycore** [comment]
@Xenega can you update that in a new PR? Thanks!

**Comment by Xenega** [comment]
@TingPing @strycore
`gtk-update-icon-cache` only update image cache for gtk. Any other desktop manager cache will not be updated. So no, it cannot replace `xdg-icon-resource`, whose value is to be independent of the specific desktop environment.

**Comment by TingPing** [comment]
That isn't true at all; Firstly there is no such thing as "cache for just gtk", this is all a standard spec. Secondly read the source of `xdg-icon-resource` it literally just calls `gtk-update-icon-cache` as that is the main implementation that exists and every distro uses.

**Comment by Xenega** [comment]
I disagree. `gtk-update-icon-cache` is a specification only for GTK 2.6+. No documentation indicate that `gtk-update-icon-cache` is becoming a standard spec. And some major distribution don't use it. For example, KDE don't use `gtk-update-icon-cache`, but don't need update (kde detect it).

However, you are right, gtk seems the only implementation used on the _official implementation_. But, xdg-utils can be tuned by distros. 

Note : 
KDE => icon-cache.kcache
GTK+ => icon-theme.cache

**Comment by TingPing** [comment]
Ok I didn't realize KDE ignored that cache. The moral of the story still is this script is just a wrapper for `gtk-update-icon-cache` and it is just an extra dependency.

**Comment by Xenega** [comment]
Yes. Do you prefer I use `gtk-update-icon-cache` if it exist ? Since it mostly a gtk problem (other desktop manager seems to do the overheard of detecting icon image change).

**Comment by TingPing** [comment]
I just see no point in using a wrapper script, that is all.

**Pull request merged**
