### PR TITLE
add fullboot and nogui opt to pcsx2

### PR DESCRIPTION
**Pull request by sigmaSd**
fix https://github.com/lutris/lutris/issues/1309

### CODE REVIEW

**Comment by krotax01** [comment]
Tested with a number of games, working fine.

**Comment by krotax01** [comment]
Given the ease for changing, I'd also include --nogui option to hide app window and return to Lutris directly when closing the game:

        {
            'option': 'nogui',
            'type': 'bool',
            'label': 'No GUI',
            'default': False,
        }

...

        if self.runner_config.get('nogui'):
            arguments.append('--nogui')

**Comment by sigmaSd** [comment]
y It feels more like making plugins xD

**Comment by strycore** [comment]
Please rebase your PR against the `next`  branch

**Comment by sigmaSd** [comment]
rebased

**Pull request closed without merging**
