### PR TITLE
Add option to disable stats in game bar

### PR DESCRIPTION
**Pull request by TotalCaesar659**
It would be useful for those who don't want to exhibit their game stats.

### CODE REVIEW

**Comment by strycore** [comment]
No.

**Comment by TotalCaesar659** [comment]
Why?

**Comment by strycore** [comment]
Because it's useless, does not add value, adds complexity and you're not going to maintain it, I will have to.

Please re-read and agree with the terms of CONTRIBUTING.md if you wish to send further patches to this project. Otherwise, I'd rather you just keep yourself from contributing.

**Comment by TotalCaesar659** [comment]
> Because it's useless, does not add value, adds complexity and you're not going to maintain it, I will have to.

Game bar that was introduced in 0.5.8 satisfies those categories: appears and disappears, consumes vertical screen space and duplicate context menu. Of course, IMHO (as your one about my PR that was direct consequence of it).

> Please re-read and agree with the terms of CONTRIBUTING.md if you wish to send further patches to this project. Otherwise, I'd rather you just keep yourself from contributing.

I just decided to start from one small PR that would be easy for me. Well, if it's not the right time for it, I'm ready to accept it. But I'm sure that option would be for those people who likes to сustomize GUI.

**Comment by strycore** [comment]
Since you have decided to completely ignore my request of reading and acknowledging the CONTRIBUTING.md file, I'm going to break it down for you.

* Do not create options unless absolutely needed
* Make a design and stick with it
* Each user option is a moving part in the project, increases the risk of future breakages 

This is not "not the time" for your patch. The time for your patch is never. You don't get to make design decisions on my behalf.
If your next patch isn't something related to the 0.5.9, I will block you from contributing to this repository.

**Pull request closed without merging**
