### PR TITLE
Updated Spanish translation

### PR DESCRIPTION
**Pull request by mbarrio**
I have updated the Spanish translation file. There are some missing strings in the .po file though, so there still remains untranslated labels and texts here and there, like the "Hide badges on icons" preference, and all the section labels in the system preferences pane ("Display", "Audio", "Input" and so on...).

### CODE REVIEW

**Comment by danieljohnson2** [comment]
Do you want your partial effort merged now, or should we wait for you to finish?

I confess, "Hide badges on icons" is one of mine, so I feel a little slighted here. Just a little.

**Comment by strycore** [comment]
No need to wait if the PR isn't marked as draft. The rest can be completed in another patch.

**Comment by danieljohnson2** [comment]
Slighted I say! Slighted!

**Comment by mbarrio** [comment]
Thanks for merging the patch. I will translate the missing strings in another patch after they get included in the .po file.

**Comment by mbarrio** [comment]
> ... I will translate the missing strings in another patch after they get included in the .po file.

It was my fault after all as I forgot to run meson and ninja before altering the es.po file. I will provide another patch in the following days. I'm sorry for the hassle @danieljohnson2.

**Pull request merged**
