### PR TITLE
Add Lutris games as steam shortcuts

### PR DESCRIPTION
**Pull request by buxel**
This PR implements functionality to synchronize Lutris games to steam by adding them as a non-steam shortcut as described in #447. 

It is implemented in `lutris.util.steam.shortcut` without being wired up to any UI yet. 

So far, it
- can be run multiple times without creating duplicates (using a tag as identifier)
- uses 'lutris lutris:rungameid/{id}' as target
- adds icons & banners (pixelated, tough)
- leaves user created shortcuts alone

The main use case is for using steam remote play with games managed by lutris.

Open questions
- [ ] Where/when to trigger this functionality
- [ ] Sometimes, the steam overlay won't work when a game is launched via lutris, see #2719 
- [ ] Steam "tags" are not visible in the UI anymore, as they have been replaced by "collections". If tags get deprecated, we should create a "Lutris" collection for imported games. I haven't found the place where those collections are stored.
- [ ] Parts of the  [vdf](https://pypi.org/project/vdf/) package has simply been copied to `lutris/vendor`. I'm not sure if adding a git submodule or a different approach is more suitable

### CODE REVIEW

**Comment by connectety** [comment]
> Parts of the vdf package has simply been copied to lutris/vendor. I'm not sure if adding a git submodule or a different approach is more suitable
Can't the vdf package just be added to the requirements?
I think you can just add it to the install_requires in setup.py:

**Comment by buxel** [comment]
As mentioned [here](https://github.com/lutris/lutris/issues/447#issuecomment-609890718), this wouldn't be suitable for Lutris. 
I'm not too happy with this solution, as well (missing tests, updates) but I'll just add the original license file to the directory for now. Any suggestion/contribution concerning this is welcome!

**Comment by stephanlachnit** [comment]
I'm not a big fan of git submodules, they make distributing the source for distro way harder (they aren't included in the source tarballs created by github). If Lutris is going to switch to meson (which was planned IIRC), it would be possible to add this as a [wrap](https://mesonbuild.com/Wrap-dependency-system-manual.html) with a meson patch (for example like [this](https://github.com/stephanlachnit/vulkanheaders-wrap)). This has the advantage that distros can either pack vdf themselves or just install it with the wrap file.

**Comment by buxel** [comment]
This looks like a promising approach. So instead of a submodule/copying code we could just add a wrap file, which would get picked up at build time?

I guess it's time to brush up my local dev environment...

**Comment by stephanlachnit** [comment]
Yep. First you need to check in the meson code (use #2725) wether the vdf module loads, and if not run `subproject('vdf')`.
However, vdf does not have meson as a build system, so it needs to be patched, i.e. a `meson.build` needs to be added.
It would also be possible to add meson support on vdf upstream, maybe they accept it.

**Comment by strycore** [comment]
I will not accept git submodules to be merged in lutris' source code

**Comment by buxel** [comment]
For now, i just took the file. I agree that submodules wouldn't be a good solution. 
Once/if meson is used in Lutris, we can reconsider this approach. Maybe we can get mesos support upstream in the vdf package so using it will be pretty straight forward.

**Comment by strycore** [comment]
No. We do not use git submodules. Ever.

**Comment by buxel** [comment]
I think we all agree here. I was talking about mesos, the solution @stephanlachnit suggested, not submodules.

**Comment by strycore** [comment]
Oh right. The Meson stuff is still alien to me but it seems to be something we should be using in the future.

**Comment by stephanlachnit** [comment]
I guess copying the file is easier for now. I'll look if I can get vdf packed for Debian, it will miss 20.04 LTS so it will be stuck here for at least another two years.

**Comment by strycore** [comment]
I'm glad for the library that it's getting into the Debian repos but that doesn't mean this lib will be available on other distros.
I do not want this vdf stuff added as a Lutris dependency unless it's in the vendor folder. I will personally rewrite the code into lutris if I have to.

**Comment by buxel** [comment]
@strycore i don't think anybody has to rewrite the code here. The single code file has been copied and  @stephanlachnit added the lincense to te proper place.

What I'm really wondering is when this functionality should be triggered and where to add an option for that.

**Comment by Lucki** [comment]
> * I haven't found the place where those collections are stored.

They're stored inside the local storage of the embedded chromium web browser.
Have fun: https://github.com/tkashkin/GameHub/pull/368/files

**Comment by liberavia** [comment]
We should make sure, that shortcuts.vdf exists and therefore know, if steam is fully installed and working
https://github.com/buxel/lutris/blob/0bac943fe1d98f37bd5aeb94c67210b1a59aa5ea/lutris/util/steam/shortcut.py#L14

**Comment by buxel** [comment]
I have not been active on this for quite a while. Times have changed and all my free time is occupied now so i don't have time to update this.If there is anybody willing to pick this up, go for it! If i can help by giving permissions on my repo, let me know (not sure if this is the right way to do it). 
-------- Ursprüngliche Nachricht --------Von: liberavia ***@***.***> Datum: 08.03.22  17:24  (GMT+01:00) An: lutris/lutris ***@***.***> Cc: buxel ***@***.***>, Author ***@***.***> Betreff: Re: [lutris/lutris] Add Lutris games as steam shortcuts (#2729) 
We should make sure, that shortcuts.vdf exists and therefore know, if steam is fully installed and working
https://github.com/buxel/lutris/blob/0bac943fe1d98f37bd5aeb94c67210b1a59aa5ea/lutris/util/steam/shortcut.py#L14

**Comment by liberavia** [comment]
I had a recent view on the code, which is a good starting point IMHO, so I would like to take over. Instead of adding all games to steam, I'd rather have an option in context and installer to add the non-steam-game.

However, as a single dad of three kids, I fully undrestand your point @buxel . Maybe I will have the one or other question while ongoing on this

**Comment by strycore** [comment]
I'd like to get this merged in before the 0.5.10 release because this is quite an important feature for the Steam deck integration.
The only conflict in this PR is the copyright file so I might just go ahead and merge it so we can have a base to build upon.

**Comment by buxel** [comment]
great :) 
@liberavia it is nice to know somebody picks up where i left off, thank you!

**Comment by liberavia** [comment]
ok, I'll start from master then

**Pull request merged**
