### PR TITLE
Don't crash if PROTON_PATH doesn't exist and find Proton in custom locations

### PR DESCRIPTION
**Pull request by Medath**
Fix possible crash introduced by #1259

### CODE REVIEW

**Comment by sigmaSd** [comment]
What about using `steam_data_dir` function from steam.py for more feature proof

**Comment by Medath** [comment]
I think `get_steamapps_dirs` or `get_game_path_from_appid` would be better. That way it can also find Proton if the default download folder in Steam is custom.

**Comment by sigmaSd** [comment]
Make sense just 1- wasn't sure that proton would also get installed in custom folder and 2 steam_data_dir is the easiest fn to extract out of the class

**Comment by Medath** [comment]
That's how I noticed the crash. My default Steam download directory is a custom one and therefore `common` in `~/.local/share/Steam/steamapps/` didn't exist. Steam downloads the Proton versions to the folder that is set to be the default.

**Comment by sigmaSd** [comment]
Nice find! , so  steam_data_dir is out, this `get_game_path_from_appid` is problematic how would we get the id steamdb, hardcode?  this `get_steamapps_dirs` looks like the best option but it will probably mean we will need to instantiate steam class in wine.py

**Comment by sigmaSd** [comment]
Guess I vote for get_steamapps_dirs, looks the easiest and best solution

**Comment by sigmaSd** [comment]
Here's my suggestion :) 

```python

PROTON_PATH = steam().get_steamapps_dirs()
PROTON_PATH = [p for p in os.join(PROTON_PATH,'common')]
```

```python
    for path in PROTON_PATH:
        proton_versions = [p for p in os.listdir(PROTON_PATH) if "Proton" in p]
        for version in proton_versions:
            proton_path = os.path.join(PROTON_PATH, version, 'dist/bin/wine')
            if os.path.isfile(proton_path):
                versions.append(version)
```

**Comment by sigmaSd** [comment]
wine under util also uses proton_path so my suggestion will result in duplication

**Comment by sigmaSd** [comment]
here is my new suggestion I think this one should do it
```python
def get_proton():
    protons = {}
    steam_dir = [os.path.join(p,'common') for p in steam().get_steamapps_dirs() ]
    for path in steam_dir:
        proton_versions = [p for p in os.listdir(path) if "Proton" in p]
        for version in proton_versions:
            proton_path = os.path.join(path, version, 'dist/bin/wine')
            protons[version] = proton_path
    return protons

PROTON_PATH = get_proton()
```

**Comment by sigmaSd** [comment]
Just a suggestion I think using a dict for proton path is better , u can avoid redundancy at the second call u will just iterate over the keys , and for utilities/wine.py it will be simple as

 if proton in version return proton path[version]

**Comment by Medath** [comment]
Ok I implemented basic functionality to find Proton versions in custom download locations. However, my code assumes that all Proton versions are located in the same directory. I think this will work good enough for most people but could possibly be improved.

**Comment by sigmaSd** [comment]
And with dict u can remove that assumption ^^

**Comment by sigmaSd** [comment]
My bad I meant runner wine u can do this ```if 'Proton' in version:
            return PROTON_PATH[version] ``` can u please try again with dict and post ur problem I don't see the issue,

**Comment by sigmaSd** [comment]
just to be clear( aka proof I'm not just annoying u :p) this is why i want dict 

1- it looks better no no redundancy 

2 - it doesn't have the aforementioned assumption

**Comment by Medath** [comment]
Ooop it got merged already. Whatever, I have tried it with a dict first but I'm kind of a noob so I couldn't really figure out how to do it. And I don't really see where the redundancy is. My only problem is the assumption that all Proton versions are in the same download directory, but I think this is almost always the case.
I guess you can improve it in a new PR now...

**Comment by sigmaSd** [comment]
if strycore like its cool ^^ as long ur assumption its true i guess it doesn't really matter^^

**Comment by sigmaSd** [comment]
thanks for ur work btw !

**Pull request merged**
