### PR TITLE
Don't crash if get_pixbuf() can't read the file

### LINKED ISSUE #3768: (default?) icons fail to load, most games missing from library
```
2021-10-22 03:57:19,122: Starting Lutris 0.5.9.1
2021-10-22 03:57:19,206: No cores found
2021-10-22 03:57:21,828: Startup complete
2021-10-22 03:57:21,831: Running Intel Mesa driver 21.1.8 on Mesa Intel(R) HD Graphics 520 (SKL GT2) (0x1916)
2021-10-22 03:57:21,832: GPU: 8086:1916 17AA:2245 (i915 drivers)
2021-10-22 03:57:22,238: Unable to load icon from image bg2
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/gui/lutriswindow.py", line 455, in update_store
    self.game_store.add_game(game)
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store.py", line 158, in add_game
    game.get_pixbuf(),
  File "/usr/lib/python3/dist-packages/lutris/gui/views/store_item.py", line 108, in get_pixbuf
    return get_pixbuf_for_game(
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/utils.py", line 128, in get_pixbuf_for_game
    return get_pixbuf(image_abspath, size, fallback=get_default_icon(size), is_installed=is_installed)
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/utils.py", line 59, in get_pixbuf
    pixbuf = pixbuf.scale_simple(width, height, GdkPixbuf.InterpType.NEAREST)
AttributeError: 'NoneType' object has no attribute 'scale_simple'
```
[GLib.GError](https://github.com/lutris/lutris/blob/f4dee7eac3baaab5a5324fab2e5186729189bba8/lutris/gui/widgets/utils.py#L50) path is faulty. `pixbuf` is `None` in it, and it calls non-existing methods. https://github.com/lutris/lutris/blob/f4dee7eac3baaab5a5324fab2e5186729189bba8/lutris/gui/widgets/utils.py#L58, https://github.com/lutris/lutris/blob/f4dee7eac3baaab5a5324fab2e5186729189bba8/lutris/gui/widgets/utils.py#L62

Should init pixbuf to proper value before calling methods.

### LINKED ISSUE #3802: Won't open configure panel with some icons
```
2021-11-03 02:59:23,691: Unable to load icon from image fl-studio
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lutris/game_actions.py", line 178, in on_edit_game_configuration
    EditGameConfigDialog(self.window, self.game)
  File "/usr/lib/python3/dist-packages/lutris/gui/config/edit_game.py", line 16, in __init__
    self.build_tabs("game")
  File "/usr/lib/python3/dist-packages/lutris/gui/config/common.py", line 70, in build_tabs
    self._build_info_tab()
  File "/usr/lib/python3/dist-packages/lutris/gui/config/common.py", line 79, in _build_info_tab
    info_box.pack_start(self._get_banner_box(), False, False, 6)  # Banner
  File "/usr/lib/python3/dist-packages/lutris/gui/config/common.py", line 155, in _get_banner_box
    self._set_image("banner")
  File "/usr/lib/python3/dist-packages/lutris/gui/config/common.py", line 195, in _set_image
    image.set_from_pixbuf(get_pixbuf_for_game(game_slug, size))
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/utils.py", line 127, in get_pixbuf_for_game
    return get_pixbuf(image_abspath, size, fallback=get_default_icon(size), is_installed=is_installed)
  File "/usr/lib/python3/dist-packages/lutris/gui/widgets/utils.py", line 58, in get_pixbuf
    pixbuf = pixbuf.scale_simple(width, height, GdkPixbuf.InterpType.NEAREST)
AttributeError: 'NoneType' object has no attribute 'scale_simple'
```

This seems to happen with the icon for "FL Studio", right click > configure to reproduce.

### PR DESCRIPTION
**Pull request by danieljohnson2**
When we can't read the pixbuf, this will now return the pixbuf for unavailable.png- which is transparent.

This is what it was doing for 'non-installed' images that could not be read. It's now doing it for all images that can't be read.

Resolves #3768
Resolves #3802

### CODE REVIEW

**Comment by hobeone** [comment]
You also need to add "if pixbuf:" before line 62.  If pixbuf is None then pixbuf.composite will fail.

**Comment by danieljohnson2** [comment]
I do? Isn't line 62 already "if pixbuf:"?

**Comment by hobeone** [comment]
Doh! I was comparing to my local copy and not master.  Sorry for the noise.

**Comment by danieljohnson2** [comment]
Ah, well. Thanks for the review anyway.

**Pull request merged**
