### PR TITLE
add fps limit support

### PR DESCRIPTION
**Pull request by sigmaSd**

### CODE REVIEW

**Comment by sigmaSd** [comment]
fix https://github.com/lutris/lutris/issues/1302

**Comment by sigmaSd** [comment]
needs testing

**Comment by Zeioth** [comment]
Tested. It works fine. The FPS limit is applied correctly inside of the game. Only if libstrangle is installed in your system.
oki

Still need two things:

* Distribute libstrangle with Lutris, so it's avaliable for everyone.
* An option to set the number of FPS from a game installer.

And optionally:

* A way to enable the Vsync features of libstrangle

**Comment by Zeioth** [comment]
In the future we could consider to add a way to enable the Vsync features of libstrangle. This would allow the games without VSync, to use it (but most games already have Vsync).

**Comment by sigmaSd** [comment]
for the installer its allready covered you can do
```yaml
system:
  fps_limit: "60"
```
distributing I guess is a good idea, I'll check out the vsync opt

**Comment by strycore** [comment]
Please rebase your PR against the `next`  branch

**Comment by sigmaSd** [comment]
rebased

**Pull request closed without merging**
