### PR TITLE
Add a duplicate game command

### LINKED ISSUE #3102: Add game cloning
I would like the ability to have multiple configurations per entry. For example, launching something like `lutris rungameid:18 --config 0` would run the pre-configured set of settings that come from the script, while `lutris rungameid:18 --config 1` would run a user-edited set of settings (for example, that disables DXVK or adds some other environment variable).

An easier (but uglier imo) fix for this would be the ability to clone an entry.

### PR DESCRIPTION
**Pull request by danieljohnson2**
This PR adds a "Duplicate" command to the game actions. This command duplicates the PGA database row and the config file, but not the game files. There's a question dialog that explains this and confirms the duplication.

This assigns a new name (and ID) to the duplicate.

Resolves #3102

### CODE REVIEW

**Comment by danieljohnson2** [comment]
Hmm. @strycore has given me a earful about the perils of having >1 PGA game associated with a service game. From my testing, maybe that's happening with this PR.

If you have a GOG game and duplicate it, that works. Go back to the GOG service view and try to start the game from there, and it will start the "first" of the two games- and which is first appears arbitrary. It may be the one with the lowest id, but it may just depend on what the SQLite query optimizer comes up with. Not sure.

Anyway, if we need the user to make an explicit choice here, this will need more work.

**Comment by strycore** [comment]
what if you unset the service and service app id when a game is cloned?
or as I mentioned on another ticket, if you get more than 1 result, you can show a dialog like LaunchConfigDialog

**Comment by danieljohnson2** [comment]
I think the dialog would be much better, and maybe I can fit that in during the long weekend.

But it that an acceptable during a beta? Or is this whole feature just going to wait for 5.11.0 anyway?

Maybe I should just clear the service stuff for now.

**Comment by strycore** [comment]
there's an opportunity to close another issue in the process ( #220 ). Forget about services, we can apply that to the whole UI and show entries by slug instead of by ID. This means there could never be a duplicate in the view and a selection dialog can be shown in every case there is more than 1 result

**Comment by danieljohnson2** [comment]
#220 does not seem obviously related: you'd want to have the dialog regardless of whether you have platform icons in the view. And platform icons don't help with duplicate games either, as they duplicate the platform information- they'd have the same badge on them.

The PR gives the games different *names* (it adds a number on the end) rather than different graphics.

But I guess you'd rather have the dialog in this PR, even though maybe it will have to await the next Lutris release before it is safe to merge.

**Comment by strycore** [comment]
I meant it would be another way of solving #220. Instead of having to draw over game banners, we can just show a single entry then show a selection when launched.

**Comment by strycore** [comment]
don't modify the launch config dialog, this is used at a game level and allows for multiple executables for a game.
instead, either subclass it or write a new similar dialog class for this purpose.

also, the game bar is going to be a problem. didn't think of that one. the game bar works at a game ID level, not slug. I don't really see a solution except ... stacking multiple game bars on top of one another? which seems like a bad solution...

**Comment by danieljohnson2** [comment]
Yes, that's what the current code would do.

When both duplicates remain, though, it will pick a seemingly arbitrary one to use. Perhaps it should use a sort so that it consistently picks the same one every time, in a predictable way.

**Comment by strycore** [comment]
yes, you should remove the service and service ID when cloning so only the initial game is linked to the service.

**Comment by danieljohnson2** [comment]
Well, that's a 'no', but that should work too. So I'll do that.

I really feel dirty with all these forced-pushes, but I can't figure out how to rebase and keep a clean set of commits in the PR without doing that. I hope it is not causing problems for anyone!

**Comment by strycore** [comment]
The feature works great and has already been very useful, thanks!

**Comment by strycore** [comment]
Possible evolution of the feature: show a dialog with a single text entry for the new name and download media for the clone with the new name

**Comment by danieljohnson2** [comment]
You're welcome.

And sure, we could ask for the new name.

But how would the new duplicate ever have different media than the original? The name does not determine what the media will be, does it?

**Comment by strycore** [comment]
The media is queried with the "slug" field, which is generated from the name with the `slugify` function. So changing the name would also generate a new slug that would allow pulling new media.
This shouldn't be specific to the duplicate command but for any time we detect a change in the slug (for example, we don't download any media when the slug gets changed in the preferences)

The specific use case I was using for is with a Need For Speed Anthology I had installed. With duplicates, I could make individual entries for Porsche Unleashed, Hot Pursuit 2, etc.

**Comment by danieljohnson2** [comment]
I see; the current Duplicate command adds a number to the name and does *not* change the slug, since adding a digit to the slug is not likely to match anything. In this way it keeps using the same media, so new download is needed.

The use case I had in mind was 'different configs, same game' not 'different games, same game files', and I think we'd want to support both.

**Pull request merged**
