### PR TITLE
"Uncategorized" automatic creation of category on game install

### PR DESCRIPTION
**Pull request by dobval**
#5339 had the cool idea, also ran "ruff format" according to CONTRIBUTING.md

### CODE REVIEW

**Comment by danieljohnson2** [comment]
I've some thoughts about this.

First, oh god look at all the reformatting. ``ruff format .`` doesn't do anything like this much for me. What happened?

Second, I'd like to suggest that your new category is not named right; it should be "Newly Installed"; games remain in the category no matter how many other categories they are put in. If we really want "Uncategorized" we'd need a very different and much more dynamic implementation (Like "Recent" has).

And it is "Newly Installed" because it covers only what is installed via our install scripts; if you add an existing game it will not be included.

And I think there's a further thing here- you can have a game that you can categorized, but which goes into the new category anyway because you have just installed it. Games that are not installed can be categorized- in the new Lutris release, with library sync on, everything in your Lutris library now appears in "Games" and *can be categorized*. But they only get put into your new category when you install them, I think.

If you really want "Uncategorized", you need to take a very different approach. But maybe this behavior is what you want?

**Comment by dobval** [comment]
I agree with the suggestion of "Newly installed" and I think a better functionality for "Uncategorized" would be, as mentioned, a dynamic category that automatically includes all the games without a user-set category in order to help list any games that a user might have missed, but still wants to categorize all of them. Any thoughts? Should I only implement a dynamic "Uncategorized" or both with "Newly Installed" About `ruff format`, weird behaviour but I can revert all the formatting if needed.

**Comment by strycore** [comment]
I've pushed a commit that reformats the whole project with the latest version of Ruff. The project had previously been reformatted with Ruff 0.2.2, that's why the change (mostly whitespace) was so large.

That being said, having to manage an "uncategorized" category will end up being a nightmare and it certainly not compatible with library syncing on the Lutris.net website. Please update your PR to use @hirak99 's suggestion which doesn't create a database entry for games without a category.

**Comment by dobval** [comment]
Alright, later today I'll add @hirak99's suggestion and change the hard-coded entry to "Newly Installed".

**Comment by strycore** [comment]
There is no need for a hard-coded entry. If we have dynamic filter, we can query all kinds of stuff. 
While we don't have  a custom UI for this kind of filtering, I think we can easily add that functionality in the search bar. 

Some examples of queries we could support:
 - installed at: last 2 months  (show games installed in the past 2 months)
 - runner: mame (show games using the mame runner)
 - category: none (show games without a category)
 - last played: 2022 (show games last played in 2022)
 - last played: >2022 (show games played after 2022)
 - year: <2007 (show games released before 2007)
 - doom year: <1996 runner: gzdoom last played: last 6 months (show games matching the string "doom" released before 1996 using the gzdoom runner last played in the past 6 months)

**Comment by dobval** [comment]
I managed to add an option in Preferences>Interface to toggle "Uncategorized", looks good.

**Comment by danieljohnson2** [comment]
A whole lot of reformatting noise still. Can you rebase this onto the current master? Might help us read it.

**Comment by strycore** [comment]
Yes, rebase against the master branch. Your PR should be changing 3 files at most. 
Also, don't create an option to disable the feature you just implemented. You wanted it, you own it.

**Comment by strycore** [comment]
Closing this PR. It will be simpler to just create a new, cleaner one.

**Pull request closed without merging**
