### PR TITLE
Properly use Gtk.Application, kill custom DBus service

### PR DESCRIPTION
**Pull request by TingPing**
Part 1 of rebasing #188

Note that this has **not** been throughly tested, just directly ported. Please try all the various command line arguments (both on main instance and secondary) to ensure everything is functional.

### CODE REVIEW

**Comment by TingPing** [comment]
Oh sorry I forgot for master we'll have to use `optparse` still instead of `Gio.Application.add_main_option()`.

**Comment by strycore** [comment]
That's awesome, thanks a lot!

**Comment by TingPing** [comment]
To be clear this did bump the GLib dependency to 2.42.

**Comment by strycore** [comment]
I'll test it against SteamOS and Debian 8 and if it runs, I'm good with it.

**Pull request merged**
