### PR TITLE
Add config option to use long platform names

### PR DESCRIPTION
**Pull request by matoro**
This PR includes a few options to support the auto-configuration of
platform name filters...first, it makes the update of platform names in
the database unconditional for all games.  I only have about 50 titles
in my library and I did not see a significant performance impact from
this, but testing would be appreciated from somebody with a larger
library.

Second, it adds a system config option to use long platform names
(Manufacturer - System) style instead of the official platform names.  A
hardcoded list of platform names is included for the most common
systems.  This option is off by default.

Thirdly there is a small change in gui/widgets/sidebar.py that I had to
make, but I'm not sure the full consequences of.  It constructs the
unfiltered list of platforms only out of the active platform names.  The
only possible negative effect I can think of is that when adding a game
that is the first on a new platform, it won't show up in the filter list
until the next application restart.

Lastly I renamed some icons and made the old names into symlinks in
order to support multiple naming conventions for the same platform.  I'm
using the short version (no manufacturer name) as the "canonical" style.

### CODE REVIEW

**Comment by matoro** [comment]
This is hopefully a good solution for https://github.com/lutris/lutris/issues/2832 .  Over time it might be expanded to include all alternate naming schemes for various platforms.

**Comment by strycore** [comment]
Remove the option and format the code and it should be good to go.

**Comment by matoro** [comment]
@strycore By remove the option, do you mean that long names should be default and unchangeable?  Because that's contrary to the decision @AlexanderRavenheart made here:  https://github.com/lutris/lutris/pull/2777#issuecomment-623141860

**Comment by strycore** [comment]
We can have options for trivial stuff like that otherwise Lutris is going to become more and more bloated.
Choose a default and stick with it.

**Comment by AlexanderRavenheart** [comment]
I'm not a fan of adding flexibility and options to naming conventions of runners and cores. We should choose one of the 3 variants mentioned in the linked issue and align all runners/cores to conform to that. The decision should take into account the maintainability effort when new runners/cores are added or existing ones are updated and preferably avoid having to keep hard coded lists in the code.

**Comment by matoro** [comment]
This has the default to use short names, i.e. whatever the runner gives.  But the runners are wildly inconsistent right now, both the Lutris ones and even within libretro itself e.g. some .info files have long-style names, some short-style names, some runners for the same platform use different conventions, e.g. Genesis vs Mega Drive or even abbreviations that other cores don't use.  If you go with that the platform filter will continue to be a mess.  The way I see it this is us providing a "canonical" platform name, or at least the option to use one.  And it's not like there's a lot of them, this wouldn't need to be updated every time a new runner is added, only when it's a new runner for a previously-un-emulated platform.

**Comment by strycore** [comment]
please update against

**Comment by matoro** [comment]
@strycore : rebased

**Comment by strycore** [comment]
thanks!

**Pull request merged**
