### PR TITLE
Revert "Update icons with Papirus logo"

### PR DESCRIPTION
**Pull request by strycore**
Reverts lutris/lutris#1501

### CODE REVIEW

**Comment by strycore** [comment]
I didn't say I was ok to replace the official logo, I said I was ok for the banner

**Comment by tannisroot** [comment]
Oh, ok, my apologies.

**Comment by strycore** [comment]
No worries

**Comment by strycore** [comment]
The papirus logo makes some important changes to the main logo so this one stays for the time being. For smaller res, the papirus one is ok

**Comment by tannisroot** [comment]
Should I make a PR that only changes the banner?

**Comment by strycore** [comment]
Yes, that would be good

**Comment by tannisroot** [comment]
Ok. Not really related, but does this mean that old logo will go into 0.5.0 release?

**Comment by strycore** [comment]
Yes

**Pull request merged**
