### PR TITLE
Added game section. exe,args,gogid,game_id,path attributes

### PR DESCRIPTION
**Pull request by hydrian**
Added game: section documentation (incomplete) 
* game_id
* gogid
* path
* exe
* args

### CODE REVIEW

**Comment by hydrian** [comment]
Not sure why a3a5821 is failing the Travis build test. Environment?

**Comment by AlexanderRavenheart** [comment]
> pipenv run isort -c -rc lutris
> ERROR: /home/travis/build/lutris/lutris/lutris/util/linux.py Imports are incorrectly sorted.
> Makefile:88: recipe for target 'isort-check' failed
> make: *** [isort-check] Error 1
> The command "make check" exited with 2.

**Comment by xordspar0** [comment]
Woo, better installer docs 👍

**Comment by hydrian** [comment]
@strycore This is being blocked PR by #2943

**Comment by strycore** [comment]
Thanks for improving the docs!

Btw, can this PR be marked as drafted until all the TODOs are completed?

**Comment by hydrian** [comment]
Honestly, that's a recipe for it never to get updated. 

Trying to source all of the functionality and document it well with a moving target (release changes) with minimal help (volunteer work) is an unrealistic task. I think we need to consider it a 'living' document. Make it well known, that the document isn't the be-all/end-all of the documentation as much as we'd like it to be. Also reference good places to get help, like Discord, IRC, or the Lutris forums. 

Also, when adding/removing functionality, make sure the version is noted in the documentation. 

I have no issue with saying a section may be missing information. Then the installer author knows to check the personal help location mentioned above.

**Comment by strycore** [comment]
Fine, I'll just finish it myself. We can't push stuff like TODOs in prod.

**Pull request merged**
