### PR TITLE
zdoom.py add config, save, and arguments. Fix skill

### PR DESCRIPTION
**Pull request by bebop350**
Added config and save file selection to the Game Options menu. Allows the user to keep multiple config and save files in different directories for different games.

#1104

### CODE REVIEW

**Comment by RobLoach** [comment]
Nice work! Should these be Runner options instead of Game options? Or is Game options intentional?

**Comment by bebop350** [comment]
Thank you. I was debating the same thing. I'm open to suggestion. 

For what it's worth, I noticed as far as ZDoom is concerned [https://zdoom.org/wiki/Command_line_parameters#](url) skill and warp selection are considered "loading options". 1 of which is on the game options area, the other the runner options. 

Looking now I see config and save launch options are considered "configuration options". The more I think about it, I would agree it's a bit more relevant to the runner. I'd be happy to add the changes there.

**Comment by RobLoach** [comment]
Hmmm, I see the save is `save0.zds`, it doesn't prefix the game name...... Should "Save Path" be game option? I think Config file makes sense as a Runner.

**Comment by bebop350** [comment]
If I understand you correctly, I  thought that naming scheme was standard behaviour? My saves both in testing with Lutris and in general are all labeled as such, but added to the user defined directory.

Save path might make a bit more sense as a game option, that's a good point.

**Comment by bebop350** [comment]
Game options with added Arguments and Save path fields:
lutrisgameoptionscut

Runner options with added Config file field:
lutrisrunneroptionscut

**Comment by strycore** [comment]
Looks good!

**Pull request merged**
