### PR TITLE
Initial commit of publish PPA GitHub workflow. (Closes #4296)

### LINKED ISSUE #4296: Ubuntu PPA misses latest version
When Installing on Ubuntu 20.04 using:
```
sudo add-apt-repository ppa:lutris-team/lutris
sudo apt update
sudo apt install lutris
```
I get version 0.5.10 which has this bug: https://github.com/lutris/lutris/issues/4256
In that thread they recommend to update to 0.5.10.1, but that one is not the latest here: https://launchpad.net/~lutris-team/+archive/ubuntu/lutris

### PR DESCRIPTION
**Pull request by Amaylia**
- Adds a new GitHub workflow that triggers on published releases.
- Adds a supporting Bash script to facilitate the building and signing process.
- Adds a new directive to the Makefile for passing a GPG key id to the make process through environment variables.

Two new repository secrets need to be created to allow these changes to function:
PPA_GPG_PRIVATE_KEY: Should contain the output of `gpg -a --export-secret-keys <keyid>`.
PPA_GPG_PASSPHRASE: Must be the passphrase that unlocks the above private key.

The PPA_GPG_PRIVATE_KEY needs to be a key that has access to https://launchpad.net/~lutris-team and _probably_ should be a unique key that is only used for this purpose, but I'll leave that up to @strycore .

### CODE REVIEW

**Comment by danieljohnson2** [comment]
This looks good as far as I can see, but @strycore should definitely take a look as it's a bit out of my experience.

**Comment by Amaylia** [comment]
Thank you for taking a look @danieljohnson2 !

**Comment by strycore** [comment]
Looks good! 
I've added a lutris-staging ppa on Launchpad, can you please open another PR that redirects all releases to this PPA and only final releases to the official PPA?

**Comment by Amaylia** [comment]
Thank you @strycore!  I created #4653 for the additional functionality, as requested.

**Pull request merged**
