### PR TITLE
Add the ability to change a game's playtime from the edit dialog

### PR DESCRIPTION
**Pull request by AdivonSlav**
So, recently I had to reinstall Lutris and I unfortunately lost my playtime information. Instead of having to resort to using a SQLite DB editor to change this, I thought it would be nice to have an addition to the game edit dialog window where you could change the playtime for each game.

I also made sure to validate the input as a separate *FloatEntry* class. The value is just the number of hours as a floating-point value, the same way it is held in the database.

### CODE REVIEW

**Review by dobval — APPROVED** [review]

**Comment by AdivonSlav** [comment]
If somebody has the time, I'd appreciate it if they reviewed the change to see if it's okay

**Comment by danieljohnson2** [comment]
I took a quick look; mostly okay.

But... what happens if the user types an invalid float in there? I see you filter the input, but I think the user could enter something like "2...22" with too many decimal points.

**Comment by AdivonSlav** [comment]
> I took a quick look; mostly okay.
> 
> But... what happens if the user types an invalid float in there? I see you filter the input, but I think the user could enter something like "2...22" with too many decimal points.

The user can't manually input that sequence due to the filter, but it's still possible to paste in an invalid value. In that case a conversion exception from string to float is thrown. I'll try and catch it manually and display a better error message

**Comment by danieljohnson2** [comment]
I mainly would wish to make sure you can't crash Lutris this way. I don't trust this sort of filtering to be 100% effective, in any case.

**Comment by AdivonSlav** [comment]
Rebased master and added a validation step in the is_valid() method that checks to see if the playtime input can actually be converted to a float. If not, it spawns an error dialog and the save process discontinues. This way, even if the initial input filtering passes, the app won't crash due to a malformed value

**Comment by AdivonSlav** [comment]
Any further edits that need to be made or is this okay?

**Comment by strycore** [comment]
This is ok, I just wanted to wait until after the 0.5.14 release to merge it

**Comment by MujoBabajic** [comment]
nicely done

**Pull request merged**
