### PR TITLE
i18n: Add Simplified Chinese translation

### PR DESCRIPTION
**Pull request by YihaoPeng**
Can work with https://github.com/lutris/lutris/pull/2947

Screenshot:
截图录屏_20200617105040

### CODE REVIEW

**Comment by strycore** [comment]
Just a small rebase and it should be good to merge.

**Comment by YihaoPeng** [comment]
> Just a small rebase and it should be good to merge.

Done.

**Comment by YihaoPeng** [comment]
A lot of translatable content was found in `__init__.py`. Surprised 😂

**Comment by strycore** [comment]
Thanks a lot!

**Pull request merged**
