### PR TITLE
Legendary runner & syncer

### PR DESCRIPTION
**Pull request by buxel**
# What?
[Legendary](https://github.com/derrod/legendary) is a client to download and play Epic Store games. @derrod, is welcoming a Lutris integration and also helping by adding features required for it. 
I'm just putting two great things together :wink: 

# Why not the original EGS as runner?
- There is no API, beside launching a game. NO control over: downloading, installing, verifying, etc.
- It is kind of a mess to work with in general, especially if you try to implement it as a runner similar to winesteam (i tried! #2523)
- It kind of works with many hacks and fiddling around, but the long term maintenance effort just frightens me. And it's not very reliable either
- A small, easy to integrate, native client with a responsive developer us just nice, isn't it? 

# What Works?
**Syncer**
- Authenticating with Epic
- Import list of games

**Runner**
- Downloading the latest Legendary release from GitHub
- Downloading & installing games
- Starting games (with and without DRM, if supported. **Legendary does not bypass any DRM**)
- Wine prefix managed by Lutris will be passed to Legendary
- Install scripts, which inherit all functionality from the wine runner

# Why WIP ?
To support a new runner, the lutris.net script editor also needs some changes. It would be great if someone from the team could have a look at it, once this implementation is considered ready to merge.

The features have been tested mostly by me and @Steinhagen. 
- [ ] It works for us, but does it work for you? **Testers welcome!**
- [ ] Not many install script variations have been tested. A very simple sample can be found [here](https://gist.github.com/buxel/66bcd15bc59c385f3b45fc870a0ea4fb)
- [ ] I have some TODO's in the code, where I'd appreciate some feedback

There some planned features of legendary to be added:
- [x] original Epic Store compatibility - point it to a EGS installation in lutris and games should be synchronized.
- [ ] when downloading large games, there is no indication of progress, except for a spinner. This seems to be a limitation for all runners, but i wanted to mention it here, in case my conclusion is wrong. Legendary provides helpful console output already, and I'd like to show it to the user when installing a game.

# More?
If we have finished the initial implementation, allowing people to create install scripts, there are more things, we can add (which we couldn't with original EGS):
- authentication could be better. It is required for the runner but right now, the syncer handles it
- game file validation
- updating games
- Epic's cloud saves

### CODE REVIEW

**Comment by derrod** [comment]
As of https://github.com/derrod/legendary/releases/tag/0.0.15 Legendary now supports synchroization with the Epic Games Launcher. This was tested with EGS installed via Lutris on Ubuntu 20.04.

**Comment by buxel** [comment]
Synchronization now works from lutris to EGS.

**Comment by 414n** [comment]
Any update on this?

**Comment by buxel** [comment]
Sadly, no. I have ceased my efforts since it does not seem to align with internal development and politics. 
There are some efforts to integrate legendary at GameHub but they also have slowed down recently. Using legendary directly seems to be sour best bet right now.

**Comment by strycore** [comment]
Putting a whole bunch of effort in code without referring to the maintainers is usually not a good Idea.
We will have Epic Store integration. Just not done this way.

**Comment by buxel** [comment]
That's one way to put it. I was in contact with @tannisroot mostly and he even encouraged me to rebase my work so it is close to upstream. The main issue was lack of feedback, which i repeatedly asked for.

There is no denying that i put quite some work in there to get it working but i did this for fun, so it's fine. I also understand that you and the team had a lot on your hands during that time - judging from discord #dev . But by no means I did not refer to the [maintainers](https://github.com/lutris/lutris/pull/2523#issuecomment-612466643). 
Please do not understand this as finger pointing, it's just a plea for more open communication to be a little more welcoming to new developers. If it wasn't for @Steinhagen, I'd given up way earlier.

**Comment by alx365** [comment]
How about a importer from legendary? I'd love to easily import my games from there. @strycore 
L

**Comment by cazzoo** [comment]
> Putting a whole bunch of effort in code without referring to the maintainers is usually not a good Idea.
> We will have Epic Store integration. Just not done this way.

Hi, just wondering if there's already something in the pipe to handle EGS integration or if we have to cope with actuel WIP work...
If we need some efforts on Legendary integration, please let everyone know, I'm pretty sure some folks may be interrested to continue started work.
Cheers

**Comment by strycore** [comment]
@cazzoo check out the master branch, the EGS integration is mostly done.

**Pull request closed without merging**
