### PR TITLE
fix: SSL CERTIFICATE_VERIFY_FAILED issue

### PR DESCRIPTION
**Pull request by rayrapetyan**
I've bumped into the issue described in: https://github.com/lutris/lutris/issues/2970 on the latest Debian (bullseye).
Proposed PR fixes this issue without the need to create `export SSL_CERT_DIR` and updating local certs.

### CODE REVIEW

**Comment by danieljohnson2** [comment]
What does this PR *do* exactly? Is this switching certificate files?

**Comment by rayrapetyan** [comment]
Yes, this helps users with a messed-up local certs to use a pure-pythonic independent way to deal with certs.
Because certifi and its certificate list is distributed with the application, it is guaranteed to be present and certificate loading should just work on any system.

**Comment by theCalcaholic** [comment]
@rayrapetyan Is this really desirable? This would break lutris in most coporate environments (which tend to use transparent proxies) if I understand you correctly.
It could be nice to have as a fallback mechanism, though

**Comment by rayrapetyan** [comment]
@theCalcaholic, could you clarify how transparent proxies may affect local certs verification?

**Comment by ntninja** [comment]
Having looked over this again, I believe the underlying issue here is that *lutris/util/http.py* uses the *urllib.request* module (and hence *http.client* and *ssl* from the stdlib in their default configuration), while everything else uses *requests* (and hence *urllib3*’s customized usage of these modules). What @rayrapetyan’s patch does is making the (indirect) *ssl* module usage in *lutris/util/http.py* more similar to that of the remaining code that uses *requests*/*urllib3* instead. It does this by forcing usage of the same certificate bundle also used by *urllib3*, by explicitly querying the path of said bundle from the *certifi* module, constructing an OpenSSL context object using this path and then using said context for all issued requests – in essence duplicating what *requests*/*urllib3* does for all the other code implicitly.

As such, I think it would be better to instead just changing the code in *lutris/util/http.py* to utilize the *requests* module, so that Lutris doesn’t have to deal with these kinds of low-level issues in the future…

@theCalcaholic: At least with system-level installs of Lutris it shouldn’t break anything, as Debian ships its own version of the `certifi` package that just points at */etc/ssl/certs/ca-certificates.crt*. (Distros doing this kind of thing is intended behaviour for the `certifi` package with the ca-certificate list shipped on PyPI being a fallback for environments where using the OS ca-certificates isn’t feasible.)

**Comment by theCalcaholic** [comment]
@ntninja Ah,I see! That's good to know. Would it still break for the flatpak version?

**Comment by ntninja** [comment]
I did some experimentation to find out how to answer your question and I’m afraid that the certificate bundle used in the Flatpak version by `ssl.create_default_context()` (and hence *urllib.request*) differs from the one returned by `certifi.where()`. In fact, it appears that the certificate list returned by `ssl.create_default_context().get_ca_certs()` in the Flatpak environment matches that of the function call outside that environment except for omitting any per-user certificates. The `certifi.where()` function (and hence *requests*/*urllib3*) on the other hand returns the list from PyPI in the Flatpak environment instead, since the Flatpak’d version isn’t patched to delegate to the system trust store. Both inside and outside the Flatpak environment per-user certificates are ignored by anything using `certifi.where()`…

So yes, this patch breaks organizationally installed system certificates for the Flatpak version of Lutris when accessing Lutris services. Any code using the `requests` package is similarly broken, but the breakage may be worked around, as far as I can tell, by setting the `SSL_CERT_FILE` environment variable – which isn’t true for this patch.

**Comment by theCalcaholic** [comment]
I mean I don't know how much of an issue this actually is, if it is at least well documented.

I just wanted to make sure it's considered.

**Pull request merged**
