### PR TITLE
 Fix SSL: CERTIFICATE_VERIFY_FAILED Web, Runtime, Resources Modules

### PR DESCRIPTION
**Pull request by kelebek333**
Fix SSL: CERTIFICATE_VERIFY_FAILED Web, Runtime, Resources Modules

https://github.com/lutris/lutris/issues/1140

### CODE REVIEW

**Comment by strycore** [comment]
It would be very nice if that does indeed solve this problem but there got to be a more elegant way to implement this, I can't just have setlocale calls dropped in random modules of the application.

**Comment by kelebek333** [comment]
I think the problem is related to the version of opensll. The problem was solved with any fix, when I installed version 1.1.1 from PPA. 

If you want, you can close this commit.

**Comment by strycore** [comment]
Oh, that's good news, I'll point people with that issue to this direction. Btw, I don't think you meant to push your translation to this PR.

**Comment by kelebek333** [comment]
Thank you very much for your interest.

I send new commit for "update tr.po".

**Pull request closed without merging**
