### PR TITLE
Added basic ability to pull custom icons and banners

### PR DESCRIPTION
**Pull request by markubiak**
- Custom icons live in ~/.local/share/icons/hicolor/32x32/apps/lutris_(slug)_custom.png
- Custom banners live in ~/.local/share/lutris/banners/custom/(slug).jpg

### CODE REVIEW

**Comment by Xodetaetl** [comment]
I'll try to review tomorrow, sorry if it's a bit slow!

**Comment by Xodetaetl** [comment]
Oh but you left out most of your changes ! Nothing much left to review. ^^

>  I added a FileChooserButton on the Game Info tab and have it setup so that it copies the file to the proper location using the banner_file_chooser.connect("file-set", self.on_custom_banner_select) function (I think this is called Gtk callbacks?) . It isn't ideal, as it will copy the file as soon as the "Open" button is pressed. I'd prefer to do this on clicking the "edit" button / on_save() function, but I'm not quite sure how.

You still need help with that ? If so it would help a bit to see your current code.

**Comment by markubiak** [comment]
Sure, [here](https://github.com/markubiak/lutris/tree/custombanner) is the branch I am working in right now.

**Comment by Xodetaetl** [comment]
Time fliiiiiiies !
Meanwhile it seems you've found how to copy the images on save, great!
Ok so just a few notes: 
- add two lines to pga.py > migrate_games() to create the fields for hascustombanner/icon
- please check your code against the PEP 8 guidelines (line length, mostly)
- adding a game manually is broken

**Pull request closed without merging**
