### PR TITLE
Added Dutch translation

### PR DESCRIPTION
**Pull request by Vistaus**
:-)

### CODE REVIEW

**Comment by YihaoPeng** [comment]
If you have not changed `fr.po` and `tr.po`, I personally recommend that you do not commit their changes. Because `ninja lutris-update-po -C transl-builddir` tends to change every `.po` file, committing files that you haven’t actually changed may cause merge conflicts.

Also I suggest you to rebase this against #2961, so that you can translate `lutris-window.ui`, which contains the text of the drop-down menu of the main window. My previous list of translatable files lost it by accident.

**Comment by Vistaus** [comment]
> If you have not changed `fr.po` and `tr.po`, I personally recommend that you do not commit their changes. Because `ninja lutris-update-po -C transl-builddir` tends to change every `.po` file, committing files that you haven’t actually changed may cause merge conflicts.

Didn't know that. Thanks for the tip, will try to remember that next time around! :)

> Also I suggest you to rebase this against #2961, so that you can translate `lutris-window.ui`, which contains the text of the drop-down menu of the main window. My previous list of translatable files lost it by accident. After the rebase, run `ninja lutris-update-po -C transl-builddir` to get these new translatable words.

This may be a dumb question, but how do I rebase it against #2961 without losing the already translated strings?

**Comment by stephanlachnit** [comment]
Copying over works, but you can also use a feature called `git rebase`, where you can rebase your commit on top of an other branch. There are plenty of tutorials only.

**Comment by Vistaus** [comment]
Alright, I updated it. Should be good now :)

**Comment by Vistaus** [comment]
@stephanlachnit But @YihaoPeng said I shouldn't include them because it could cause merge conflicts...

**Comment by stephanlachnit** [comment]
And he is absolutely right, you shouldn't include the _changes_ to these files. You want to leave them untouched, that's why I gave you the tutorial. Take a look at the diff on Github, you added about 4000 lines to `po/fr.po` and `po/tr.po` without translating them. You don't want to do that, you just want to leave these files alone. Just because they change on disk, doesn't mean you need to commit them.

First, run:
```sh
git rebase -i bde6bfc01c77d2e49756a4c705d8e61c3e90d85e
```
This should open a terminal with three lines starting with `pick`. Now change the last two `pick` to `f`, so that it looks something like
```
pick 669af63b5b1d44aa34cb0065da57baaa79d2def4
f b6c915b1f093c6a330de1348e3ece951a0dc40ed
f abb4ecdf0c1613fbce67408a25070bf11f9adb63
```
and save it (I hope you have nano set as your git editor, else you might want to do that first before you can't exit vim anymore).

This will combine the three commits into one commit. Then, do as I said above to _only_ commit changes to the files you actually want to edit.

**Comment by Vistaus** [comment]
I always work the way I do and no one ever complained about it, but I never really come across any project using ninja to update the po files. I guess I have to re-learn some stuff for ninja then :)

Anyway, it should be good to merge now.

**Comment by stephanlachnit** [comment]
> Anyway, it should be good to merge now.

No it is still not, take a look at the diff here: https://github.com/lutris/lutris/pull/2958/files
I don't want to be offensive, but if you don't enough about git to properly commit your contribution, just follow my tutorial.

**Comment by Vistaus** [comment]
I find that a little bit offensive as you can see on my profile that I contribute to many projects, and no one ever complains about the way I commit stuff. So clearly I do know enough. I'll start over and open a new PR, that's much easier than rebasing which apparently failed.

**Comment by stephanlachnit** [comment]
> I find that a little bit offensive 'cause as you can see on my profile I contribute to many projects, and no one ever complains about the way I commit stuff. So clearly I do know a thing or two about committing. I just don't know anything about rebasing.

I'm sorry I didn't want to be offensive. Don't take it personal, rebasing commits in git is not straight forward and it took me a long time to understand it as well. I just wanted to offer my help.

> But I'll start over from scratch and open a new PR, that's much easier than rebasing which apparently failed.

Just try to not stage `po/fr.po` and `tr.po`.

**Comment by YihaoPeng** [comment]
I am sorry for these arguments, but the easiest way is probably this:
```
# reset git index to lutris:master
# Your changes will not be lost, they will remain in the working directory and appear as differences
git reset daea91a36340a41927deac2b87deeee1738c74ce

# only add files that you actually changed
git add po/LINGUAS
git add po/POTFILES
git add po/nl.po

# commit
git commit -m 'Added Dutch translation'

# force push
git push --force-with-lease
```

**Comment by YihaoPeng** [comment]
Or if you want to rebase (this method is very rough, very manual, but it's simple):
```
# add my repo
git remote add tiger https://github.com/SwimmingTiger/lutris.git

# fetch my branch
git fetch tiger zh_CN_trans

# change your base
git reset tiger/zh_CN_trans

# Please manually edit `po/LINGUAS` and add `zh_CN` to the end.
# Because we used reset, my changes were not merged.
# But you can see my changes from `git diff po/LINGUAS`.

# add files you changed
git add po/LINGUAS
git add po/nl.po

# commit
git commit -m 'Added Dutch translation'

# force push
git push --force-with-lease
```

**Comment by Vistaus** [comment]
Thanks for the explanation, but I already opened a new PR: https://github.com/lutris/lutris/pull/2962

**Comment by Vistaus** [comment]
@stephanlachnit I understand. Water under the bridge :)

**Pull request closed without merging**
