### PR TITLE
make scripts cwd default to $GAMEDIR + fix post script bug

### PR DESCRIPTION
**Pull request by sigmaSd**
fix  https://github.com/lutris/lutris/issues/1299

### CODE REVIEW

**Comment by sigmaSd** [comment]
on-demand script will default to $GAMEDIR

**Comment by tannisroot** [comment]
Nice! @strycore can this be merged if everything is fine and released with 0.4.22.1? There is a very, very critical issue with DXVK with one game that needs this function working properly, badly.

**Comment by sigmaSd** [comment]
post script has to be executed after self.stop() or else it will be immediately killed

**Comment by tannisroot** [comment]
With this, the working directory is still not gamedir. If I make a script that does this `mkdir ./test`, it now create a `test` directory where the game executable is, not in ~/Games/any_game.

**Comment by sigmaSd** [comment]
oups, should be fixed now would you test again?

**Comment by tannisroot** [comment]
Yep, works great now.

**Comment by sigmaSd** [comment]
thx for testing :)

**Pull request merged**
