### PR TITLE
check hash for download installers

### PR DESCRIPTION
**Pull request by duhow**
Implements #1218 - not sure if this is enough to close it.

Using [6 Days A Sacrifice](https://lutris.net/games/install/3246/view) as example, we add `checksum`:

```yaml
  files:
  - game:
      filename: 6days_se.zip
      url: http://www.g4g.it/files3/2009/FullyRamblomatic_SpecialEditions_www.g4g.it.zip
      checksum: md5:5a546c58dd0323a6dcbc31dfcd90c339
```

### CODE REVIEW

**Comment by danieljohnson2** [comment]
Does this work with InstallerFileCollection? I feel like this will crash for any GOG or Amazon game, since they use that instead.

**Comment by duhow** [comment]
I don't expect any compatibility issues, as the function seems to run only if checksum is defined.

https://github.com/lutris/lutris/blob/1492c47749cdc41b435ca445ae08632ffd77bb18/lutris/installer/installer_file.py#L216-L217

**Comment by danieljohnson2** [comment]
That looks better.

**Comment by danieljohnson2** [comment]
Even if ruff doesn't think so!

**Pull request merged**
