### PR TITLE
Hide Discord Presence options

### PR DESCRIPTION
**Pull request by isugimpy**
…res which are disabled due to lack of requirements.  Hide Discord functionality when pypresence not installed.

Returns Discord Presence functionality to being hidden until ready for release.

### CODE REVIEW

**Comment by strycore** [comment]
This is not what I wanted and is way too complex.
Remove the Discord option from the system options, and attach them conditionally.

**Comment by isugimpy** [comment]
Can do.  Will have it up shortly.

**Comment by isugimpy** [comment]
Sorry for the misunderstanding there.  Sometimes I get a little overzealous and overshoot the mark.  This set of changes I think handles it the way you requested, and is far simpler.

**Comment by isugimpy** [comment]
@strycore Not sure if you saw that these changes are up.

**Comment by strycore** [comment]
Nice! Thanks!

**Pull request merged**
