### PR TITLE
(i18n) Update pt_BR translation

### PR DESCRIPTION
**Pull request by kassindornelles**
Full Portuguese (Brazil) translation

### CODE REVIEW

**Comment by kassindornelles** [comment]
Okay, after some small fixes here and there everything looks correct and i'm pretty happy with it

**Comment by danieljohnson2** [comment]
I think there's still a mistake on line 4347, though I don't speak Portuguese. But I think you have rendered "If blank or 'auto'," as "Se estiver em branco ou 'automático'," and the thing is it actually expects the exact text "auto", not anything longer, here.

Perhaps this string should be localized, but it isn't- and there are other examples like it in the settings where the translation has 'auto'

**Comment by kassindornelles** [comment]
> 

is that line the only one that you saw a problem related to "automatico"?

**Comment by danieljohnson2** [comment]
Yes, that's all I spotted. Though for all I know "automático" means "pickled herring".

**Pull request merged**
