### PR TITLE
Fix typo in file name: LICENCE → LICENSE.

### PR DESCRIPTION
**Pull request by Freso**

### CODE REVIEW

**Comment by RobLoach** [comment]
:+1:

**Comment by strycore** [comment]
This will probably make some Brithish people angry. I'll merge it.

**Comment by Freso** [comment]
Well, the rename from `COPYING` to `LICENCE` was in the name of standardisation. I've seen `COPYING` in plenty of projects, but I'm not sure I've ever seen `LICENCE`… :)

**Comment by strycore** [comment]
Yes, licence is a valid British (and also French) spelling but it's never used in software projects. I used to make that mistake a lot as well, now I just google the word if I'm unsure :p

**Pull request merged**
