### PR TITLE
Add .desktop file's path variable to the working directory field on local source games

### LINKED ISSUE #5325: Lutris can not launch a game through a .desktop file
Hello, first of all thank you for the amazing work you have done in the linux gaming scene.

When Lutris imports a game from the local source (a desktop file in .local/share/applications), it can not be launched.
I am using ULWGL for launching the game through the desktop file.

[Desktop Entry]
Type=Application
Categories=Game
Name=Grim Dawn
Icon=/usr/share/icons/Papirus-Dark/16x16/places/folder-games.svg
Path=/HDD/GranAlmacen/Juegos/Grim Dawn
Exec=env GAMEID="" WINEPREFIX="/HDD/GranAlmacen/Juegos/Grim Dawn/wine" ulwgl-run-cli "x64/Grim Dawn.exe"

Cheers !

### PR DESCRIPTION
**Pull request by Aqa-Ib**
This is working. Telling the truth I don't write python code, so I had help from chatgpt, so review the code before committing.
Fixes #5325

### CODE REVIEW

**Comment by strycore** [comment]
This is such an ugly solution, probably explains why I didn't want to implement it in the first place. The rest of the code uses the Gio.AppInfo class and for this one bit we have to resort to reading the .desktop file to make up for the shortcomings of Gio. 

We might as well consider not using the Gio.AppInfo class at all and build our integration by manually parsing .desktop file. If we're doing that anyway why not go all the way.

Anyway. Thanks for the patch. Ugly and working is better than good looking and not working. It's not like the XDG integration gets a lot of use anyway.

**Comment by danieljohnson2** [comment]
Well, I don't like the use of regular expressions for this. I think we should call ``xdg_app.get_string("Path")`` rather than reading the file. It would look like this:

```python3
    @staticmethod
    def get_desktop_entry_path(xdg_app):
        """Retrieve the Path variable from the .desktop file"""
        return xdg_app.get_string("Path")
```

Can you make that change?

**Comment by danieljohnson2** [comment]
I guess not; @strycore just merged this. I'll change it in master.

**Comment by strycore** [comment]
> I think we should call xdg_app.get_string("Path") rather than reading the file.

Where is this documented?

**Comment by danieljohnson2** [comment]
I found it [here)(https://lazka.github.io/pgi-docs/Gio-2.0/classes/DesktopAppInfo.html)

But let me see if I can find something more official.

**Comment by danieljohnson2** [comment]
I think [this](https://docs.gtk.org/gio/method.DesktopAppInfo.get_string.html) is the official docs.

**Comment by strycore** [comment]
How did you figure out that this was the method used to get the Path value? Do you have some kind of divination power?

**Comment by danieljohnson2** [comment]
It is not specifically for the path value, it pulls out one of the values by key. I found no more specific method than this; but at least it beats a RegEx on the file content.

**Comment by strycore** [comment]
> I think [this](https://docs.gtk.org/gio/method.DesktopAppInfo.get_string.html) is the official docs.

Gtk really has the worst documentation any API has ever had. I'm so ashamed of using a toolkit that is that bad.

**Comment by danieljohnson2** [comment]
Yeah, it's not great that way. It's painfully short of samples, and the references docs aren't 100% complete either. And they keep changing it.

**Comment by danieljohnson2** [comment]
I've updated this in master. Thank's for the PR @Aqa-Ib.

**Pull request merged**
