### PR TITLE
Adding gog language installer selection by locale

### PR DESCRIPTION
**Pull request by liberavia**
Hey there,

I used this cool feature of automatically downloading gog files the first time for Witcher III. It worked great, but as I ran the game, I noticed that spoken language is english. I remembered that they told this in the news back then. 

However, I think this little patch can hopefully do the trick.

### CODE REVIEW

**Comment by strycore** [comment]
This looks good, please sign the CLA so I can merge the patch.

**Comment by liberavia** [comment]
Hi
please notice that I did not test this yet. Is there any guide for setting up a dev-environment where i can test things without touching my global installation?

**Comment by strycore** [comment]
You can run lutris directly from the source tree: `cd Projects/lutris; ./bin/lutris -d`

**Comment by liberavia** [comment]
That was too easy :grinning: 
I'm testing right now with witcher III goty. At least it seems to grab the right files:
Selection_034

I will tell if it worked finally on my machine.

**Comment by strycore** [comment]
Would this still work if your computer had a locale that isn't supported by the game?

**Comment by liberavia** [comment]
To be sure I will test the fail-scenario too, but I will take another game then. However, the programmed behaviour of my patch is semi-optimal, a quick-hack because I want to use this. A quite better way would be to offer a language selection by determing the available languages for the game. I will have a look on this as soon I understand how the gog-download dialogue is implemented. But this will be a story of another PR :grin: For now I just check that it won't break anything

**Comment by liberavia** [comment]
Having the right language ootb is not only about the installers. Sadly I still experienced english language despite using the "right" installers (in fact they seem to be exacly the same). There is a need of loading the language packs additionally. They are listed seperately in the json (In my example: https://api.gog.com/products/1495134320?expand=downloads )
Selection_035

**Comment by liberavia** [comment]
OK I am now 1 step further. It seems that having language packs is more exception then common on gog. At least none of my games (except W3) is providing installers that inlcude language abilities of the game.

My latest push is a work in progress (wp) because I currently don't now how realizing the execution of the downloaded language patch after the general gog-setup.

I'm spinning in circles because I don't understand how file_id "gogsetup" is mapped to the .exe installer. I mean this process:

```
DEBUG    2021-01-24 22:37:02,876 [downloader.download_cb:99]:Finished downloading https://content-system.gog.com/products/1495134320/users/46987682196037121/namespaces/website/download?path=%2Fsecure%2Fwitcher_3%2Fgoty%2Fclassic%2Fsetup_the_witcher_3_wild_hunt_goty_1.31_%28a%29_%289709%29.exe&token=eyJhbGciOiJIUzI1NiIsImV4cCI6IjE2MTE2MTA2MTcifQ.eyJjb250ZW50Ijoie1widXNlcl9pZFwiOjQ2OTg3NjgyMTk2MDM3MTIxLFwicHJvZHVjdF9pZFwiOjE0OTUxMzQzMjAsXCJwYXRoXCI6XCJcXFwvc2VjdXJlXFxcL3dpdGNoZXJfM1xcXC9nb3R5XFxcL2NsYXNzaWNcXFwvc2V0dXBfdGhlX3dpdGNoZXJfM193aWxkX2h1bnRfZ290eV8xLjMxXyhhKV8oOTcwOSkuZXhlXCJ9IiwiZXhwIjoiMTYxMTYxMDYxNyJ9.XOjqLMbXHc9I88_4lZb7HyyIy6bUIZuZd2fWEgwBxeY&access_token=MgkuE5s-dYvBIUhpaBi_Aw2t6IgA8oZKmHCGB7bqkhLZ-xCMcCWRjEo1rA3Ok5JPl9VOJHN2xSW56dF-ynhNd9PYSl7ERLiywxjpNUSSTLC-UIwB1uQ7Eik6a1DezKu3ozDwm4RfnyanSvPuYS1f0Q
DEBUG    2021-01-24 22:37:03,331 [files_box.on_file_available:78]:gogsetup is available
```

The file_id seems to be originated at teh maching install-script:

```
[
   {
      "id":12494,
      "game_id":26345,
      "game_slug":"the-witcher-3-wild-hunt-game-of-the-year-edition",
      "name":"The Witcher 3: Wild Hunt - Game of the Year Edition",
      "year":2015,
      "user":"citrusalex",
      "runner":"wine",
      "slug":"the-witcher-3-wild-hunt-game-gog",
      "version":"GOG",
      "description":"None",
      "notes":"",
      "created_at":"2019-03-24T06:18:18.640000Z",
      "updated_at":"2020-12-20T17:05:06.068401Z",
      "draft":false,
      "published":true,
      "published_by":494,
      "rating":"",
      "steamid":292030,
      "gogid":1495134320,
      "gogslug":"the_witcher_3_wild_hunt_game_of_the_year_edition_game",
      "humbleid":"",
      "humblestoreid":"",
      "humblestoreid_real":"the-witcher-3-wild-hunt",
      "script":{
         "files":[
            {
               "gogsetup":"N/A:Select the game's setup file"
            }
         ],
         "game":{
            "exe":"drive_c/GOG Games/The Witcher 3 Wild Hunt GOTY/bin/x64/witcher3.exe",
            "prefix":"$GAMEDIR"
         },
         "installer":[
            {
               "task":{
                  "name":"create_prefix",
                  "prefix":"$GAMEDIR"
               }
            },
            {
               "task":{
                  "args":"/SP- /NOCANCEL /SUPPRESSMSGBOXES",
                  "description":"Installing Witcher 3",
                  "executable":"gogsetup",
                  "name":"wineexec",
                  "prefix":"$GAMEDIR"
               }
            }
         ],
         "system":{
            "env":{
               "__GL_SHADER_DISK_CACHE":1,
               "__GL_SHADER_DISK_CACHE_PATH":"$GAMEDIR"
            },
            "pulse_latency":false
         },
         "wine":{
            "Desktop":true
         }
      },
      "content":"files:\n- gogsetup: N/A:Select the game's setup file\ngame:\n  exe: drive_c/GOG Games/The Witcher 3 Wild Hunt GOTY/bin/x64/witcher3.exe\n  prefix: $GAMEDIR\ninstaller:\n- task:\n    name: create_prefix\n    prefix: $GAMEDIR\n- task:\n    args: /SP- /NOCANCEL /SUPPRESSMSGBOXES\n    description: Installing Witcher 3\n    executable: gogsetup\n    name: wineexec\n    prefix: $GAMEDIR\nsystem:\n  env:\n    __GL_SHADER_DISK_CACHE: 1\n    __GL_SHADER_DISK_CACHE_PATH: $GAMEDIR\n  pulse_latency: false\nwine:\n  Desktop: true\n"
   }
]
```

I just can't find where the single file (of a list of files) is set to be the id of gogsetup. Any good advice where I could trace this?

**Comment by strycore** [comment]
To understand how the `gogsetup` file is converted to a list of GOG downloads, you have to read `prepare_game_files` in installer.py. We take the first file with `N/A` in the URL and replace that file with a list of GOG files.

As for offering the option to have the language selected by the user, I would rather not at the moment. We have a lot of installers that do have a language selector that has been manually written. We can't have 2 competing systems for the same thing. 
As I want to move from installer script to a more metadata based approach, we can offer a list of available languages from either the GOG API or a list of locales that are supported by a game and manually entered by a script maintainer. 
With that in place we can combine the 2 and find out a way to have fully-automated installs that select the best choice for the locale automatically or have it shown during install time as a configuration option.

**Comment by strycore** [comment]
There's also a bunch of attributes that we have to add support to in GOG. The most important one is `patches`. Once we add support for `patches` in the GOG API, it would be trivial to support `language_packs` as well. For now, I would suggest to only focus on games that have localized installers and deal with language packs later.

**Comment by liberavia** [comment]
Thx for the explanation. I reverted my attempt to fetch those langpacks and finally tested the origin patch against Abe Odyssee, which only has an english installer. It worked as expected (Fallback behaviour).

And, as said, most of the games will be fully localized by picking the right installer. So if you are d'accord, you can merge this one. I won't change this branch for now.

**Comment by liberavia** [comment]
Ah you're implementing CI :+1: I guess the fail has nothing to do with my patch at the moment?

**Comment by liberavia** [comment]
> As I want to move from installer script to a more metadata based approach, we can offer a list of available languages from either the GOG API or a list of locales that are supported by a game and manually entered by a script maintainer.
> With that in place we can combine the 2 and find out a way to have fully-automated installs that select the best choice for the locale automatically or have it shown during install time as a configuration option.

Full ack. Opened an low-prio-issue, so that we can take care later: https://github.com/lutris/lutris/issues/3381

**Comment by strycore** [comment]
The CI failure is due to Travis trying to download the runtime, which it shouldn't be doing. Once I fix that, Travis should be ok.

**Comment by liberavia** [comment]
Hey @strycore . Hope you're still well. When is this planned to be merged approximately?

**Pull request merged**
