### PR TITLE
Fix updates with itch.io

### LINKED ISSUE #4740: itch.io can't update games
Headline says all. 

It throws a 400 error and has issues downloading the files.
I wrote the itch.io service and make this issue mostly to let others know that I am already on it and will submit a merge request within the next couple days.

tbh I dropped the ball here as I barely tested this feature. Sorry about that.
In my only defense: I didn't have a game to update which has now changed as of a couple hours ago.

### PR DESCRIPTION
**Pull request by GoGoOtaku**
Some rewrites to fix updating.

As an aside: The sqlite database does not store when a game was updated. `installed` is set when a game is first installed and I couldn't find when `updated` is ever set. Not sure if this is wanted or not but it is outside the scope of the itch.io service and thus I made a "workaround" by saving the date in the meta file I already placed in the install directory.

This will close #4740

### CODE REVIEW

**Comment by danieljohnson2** [comment]
I have to say, this is the best line of code ever:
```
uploads = [upload["upload"] if "upload" in upload else upload]
```

**Comment by danieljohnson2** [comment]
Still, looks like a legit fix for the 400 error, so I'll merge this.

**Comment by danieljohnson2** [comment]
Pylint tells me the method '_check_outdated_in_db' is not there. I think you meant _check_update_with_db, so I'll make that change. Please advise if that's not correct.

**Comment by GoGoOtaku** [comment]
Yes indeed. tbh I struggled a bit having a readable name for the function and renamed it. And it seems I forgot to rename it there.

**Pull request merged**
