### PR TITLE
Implementation of Discord Rich Presence, along with some typo/flake8 …

### PR DESCRIPTION
**Pull request by isugimpy**
…fixes

Got the wild urge to write this for myself, figured it might be useful to the community.  Turns out there is/was an open issue for a feature request on it a while back  https://github.com/lutris/lutris/issues/826

### CODE REVIEW

**Comment by isugimpy** [comment]
Apologies for the messiness here.  I'm closing this back out for now.  Apparently pypresence isn't 3.5 compatible.  I'm going to see what I can do about this.

**Comment by strycore** [comment]
no need to close it :) you can say when it's ready for review, we'll leave it here until then!

**Comment by isugimpy** [comment]
@strycore Thanks!  Reopened.  I got the pypresence maintainers to release a newer version of the package, it was actually unintentional that the previous release wasn't 3.5 compatible.  This code has been tested pretty extensively locally over the last couple days and seems to work very well.  Not certain that it meets all the design considerations of the project, but I think it's ready for review.

For clarification of intent:

- Allows users to set their presence on Discord automatically
- Uses a default app ID (which I've created, feel free to replace it) that presents a game name of "a game through Lutris"
- Uses the Lutris game name by default
- Provides a secondary detail which indicates the runner the game is running under
- Allows you to override per-game the app ID, game name, and visibility of the runner
- Allows you to disable showing the runner and the Discord update entirely

Example attached below:
Screenshot_20190509_214613

**Comment by PythonicChemist** [comment]
Perhaps extracting the Discord Rich Presence feature out of the Game class would be good since the Game class is already pretty big and the feature would add another 100+ lines to it.

Awesome feature and I am sure many people on Discord are looking forward to it. :+1:

**Comment by isugimpy** [comment]
On the one hand, I agree with you because it increases file complexity significantly as is, and it'd make it significantly more testable. On the other, it's a very integration-heavy feature, and it seems to me that it's a behavior of the game class itself. The game is notifying Discord that it's running and no longer running. I also don't see a situation where anything else in the codebase would consume this code, which reduces the value of extracting it into its own class. I'll do what's best for the project and desired by the maintainers, at the end of the day, but I just don't know if the time investment of that provides real gain.

**Comment by telanus** [comment]
Just a question, how will this work with systems that already feature discord's DRP? IE MAME, PPSSPP & Retroarch?

**Comment by isugimpy** [comment]
You just disable it on those. Things like that are one of the big reasons I offered a toggle for it. :)

**Comment by isugimpy** [comment]
@strycore I think the latest two commits address your review.  Added the dependency to extras_require.  The config options get hidden if the dependency isn't present on the system, and it just logs that the feature isn't enabled.

**Comment by strycore** [comment]
Nicely done! Is the default client id something I need to change?

**Comment by isugimpy** [comment]
@strycore You don't necessarily NEED to, I have no intention of changing any settings on it. But if you want to, absolutely feel free. It might be wise to have the ID owned by a member of the team, in case any additional features get added on the Discord side which could be taken advantage of. I'm hoping this is the first of many contributions by me to the project, though, so I have no problem with holding onto the ID. Basically, do what the team feels makes sense. :)

**Comment by strycore** [comment]
Thanks for clarifying. As you said, this would be better to have as an asset owned by the team. I'll create an app before shipping this feature.

**Pull request merged**
