### PR TITLE
fix gog icon size in left panel

### LINKED ISSUE #3217: GOG icon is massive
Trying out the latest 0.5.8 beta, the GOG icon is massive. 

https://imgur.com/a/vaFphwE

Don't think I need to explain more than that...

### PR DESCRIPTION
**Pull request by LiamDawe**
It's way bigger than all the others. This solves it.

Fixes #3217

### CODE REVIEW

**Comment by Newbytee** [comment]
You can put "Fixes https://github.com/lutris/lutris/issues/3217" in the body of this to automatically close your issue when this gets merged.

**Comment by LiamDawe** [comment]
> You can put "Fixes #3217" in the body of this pull request to automatically close your issue when this gets merged.

Clever, didn't know that. Added. Cheers.

**Comment by strycore** [comment]
wtf.

**Comment by strycore** [comment]
gog icon is downloaded by the runtime

**Pull request closed without merging**
