### PR TITLE
Category feature

### PR DESCRIPTION
**Pull request by Riesi**
Ok I feel a bit stupid for messing up  and having to do a new pull request. 
This code should be much better in regards to quality and efficiency.

- SQL tablse for categories and m2m relationship
- REFERENCES in a very basic way
- UNIQUE constraint; only single entry constraint for now, because else stuff broke
- sidebar entries for categories
- entry in the right click menu
- dedicated window for adding and selecting categories
- excessive, leading and tailing whitespaces get removed
- categories get deleted, if they have no entry in the m2m table

screenshot

### CODE REVIEW

**Comment by tannisroot** [comment]
I think "WIP" part should be dropped since you are not actively improving the PR.

**Comment by Riesi** [comment]
I think WIP still fits, since I dont think this is completely ready.
But more feedback would be great for that, because I don't know what you guys like and what not.

**Comment by tannisroot** [comment]
Yeah but I feel like WIP kind of implies it is not ready even for a review.

**Comment by Riesi** [comment]
Ahh ok that also makes sense! Rebased it onto latest next.

**Comment by tannisroot** [comment]
I think it should be rebased against master now, btw.

**Comment by strycore** [comment]
Pushing back to 0.5.3 because there is a lot to review. I'll merge this in a separate branch and to the review from there. You can then submit other PRs against that branch once I've created it.

**Comment by strycore** [comment]
This is now merged in the `categories` (https://github.com/lutris/lutris/tree/categories) branch and PRs related to this feature can be submitted against that branch.

**Pull request closed without merging**
