### PR TITLE
Make sure the view gets re-sorted on config change, as game gets 'add…

### LINKED ISSUE #1184: Changing configuration with "Installed games first" sorting option puts the game at the bottom
This is quite weird behavior that should be fixed.
peek 2018-10-13 15-50

### PR DESCRIPTION
**Pull request by Tom-Todd**
…ed' again to the store.

Also, change sort_view method, so that it sorts by name first then by installed first if enabled
so that positioning is consistent.

Fixes #1184

### CODE REVIEW

**Comment by TingPing** [comment]
This is a weird workaround, every insert should internally resort in the model.

**Comment by Tom-Todd** [comment]
> This is a weird workaround, every insert should internally resort in the model.

"internally resort in the model" I'm not sure I understand what this means

**Comment by strycore** [comment]
I'm merging this for the release as it seems to work but a proper implementation would be nice.

**Comment by TingPing** [comment]
Glancing at the source of Gtk really quick the actual solution would be to change `self.store.append` to `self.store.insert_with_values` and that will properly resort after inserts.

**Pull request merged**
