### PR TITLE
add playtime to lutris

### PR DESCRIPTION
**Pull request by sigmaSd**
hopefully this is rebased !

### CODE REVIEW

**Comment by sigmaSd** [comment]
this has one flaw, It only update the time on the gui if you exit the game with lutris stop button, otherwise if you quit the game normally you will need to restart lutris to see the time change.
To update it at game exit I need  to add it to `def refresh_status` but not sure if its worth the overhead

**Comment by sigmaSd** [comment]
I fixed the flaw , and add a check to remove overhead

**Comment by sigmaSd** [comment]
sorry about the commit history didn't figure out how to fix it

**Comment by PythonicChemist** [comment]
You can do "git rebase -i HEAD~NO_OF_COMMITS_TO_SQUASH" to clean up commit history of your branch. Look up how to squash in git.

**Comment by sigmaSd** [comment]
I understand, I prefer I skip this time if its not really needed cherry picking interesting commit is not fun xD , but if its necessary i'll do it

**Comment by sigmaSd** [comment]
Nvm i'll give it a shot

**Pull request closed without merging**
