### PR TITLE
Simplify copyright of Lutris

### PR DESCRIPTION
**Pull request by strycore**
Over time, the project has gathered a lot of different files from different sources.
With Debian being who they are, this is creating friction in getting the project into the official repositories.

This pull request simplifies the ownership of files in the project. Any file not owned by myself has been removed.

We can circumvent abusive copyright rules by having the client download resources such as icons at runtime.

### CODE REVIEW

**Comment by strycore** [comment]
This unblocks #2553

**Comment by strycore** [comment]
It's not viable to manage icons for all platforms and runners from the client itself anyway. Especially now that we have json runners

**Comment by strycore** [comment]
Icons are now downloaded as part of the lutris runtime

**Comment by stephanlachnit** [comment]
Cool, thanks!

**Pull request merged**
