### PR TITLE
added greek translation

### PR DESCRIPTION
**Pull request by Pyrofanis**
for any issues please contact me

best regards
pyrofani

### CODE REVIEW

**Comment by danieljohnson2** [comment]
Well, looking at this what I see is a grammar error in the English text. "By default, it use the directories in the ..." should be "By default, it will use the directories in the ...". I'll fix that, but that'll break your .po file.

@strycore has told me not to tamper with .po files to 'fix' them, so I'll leave this to people who know what they are doing.

**Comment by strycore** [comment]
@danieljohnson2 the grammar error is likely in the code itself and that's where it has to be fixed. Then the po files can be re-generated with the fixed string.

**Comment by danieljohnson2** [comment]
I fixed it in the code.

**Comment by Pyrofanis** [comment]
ok guys
so what steps should I take to correct the translation after the grammatical error fix ?

**Comment by danieljohnson2** [comment]
It looks like the README.md file describes 'Updating a translation', which says you do this:
```sh
meson builddir
ninja lutris-update-po -C builddir
```

And that updates all .po files.

**Comment by Pyrofanis** [comment]
ok going to resolve it asap thanks 👍🏼

**Comment by Pyrofanis** [comment]
ok two strings needed to be updated 
i only pushed the updated el.po file to not mess with other translations 
also deleted the first 5 lines containing the copyright

**Comment by Pyrofanis** [comment]
nope is certainty not thanks daniel for pointing  them out

**Comment by Pyrofanis** [comment]
found some more strings that needed to be adjusted

**Pull request merged**
