### PR TITLE
add playtime

### PR DESCRIPTION
**Pull request by sigmaSd**
commit history got really ugly so this was the easiest way 
history:https://github.com/lutris/lutris/pull/1235

### CODE REVIEW

**Comment by strycore** [comment]
It's one way to do it but not the only way, here's a time machine for next time ;) 

https://git-scm.com/book/en/v2/Git-Tools-Rewriting

**Comment by tannisroot** [comment]
@sigmaSd  I don't like that you can only see playtime in a List mode, the feature is useless in the Grid mode, which is default and what most users use.

**Comment by strycore** [comment]
that feature is barely in prototype stage

**Comment by sigmaSd** [comment]
@strycore thanks for the link I'll keep it in mind for next time :) , @tannisroot I agree with  but its like @strycore  said and I'm thinking in the future maybe lutris will get a nice side bar that shows game preview (video image screenshot) and underneath it game info . and anyway gathering playtime info from now is good idea everyone like statics ^^

**Pull request merged**
