### PR TITLE
DRM-be-gone!

### LINKED ISSUE #3950: [Feature Request] Option to add locally installed games in the Lutris Source view
Currently you can only install games, and it works for installable games, but it's cumbersome at rom based games. 

A better idea would be to have an option to add "locally installed games" to the entry

### PR DESCRIPTION
**Pull request by danieljohnson2**
This removes the DRM-free flag. This merely enables the "Locate installed game" command for every source- it does not enable you to install anything you couldn't before.

I don't think giving only GOG and Humble-Bundle sources the "Locate installed game" command makes a lot of sense; this command does not let you install a DRMed game at all. You would install it via another method, perhaps the Steam client say, and this command would make it easier to connect that game to Lutris.

And anyway, even Steam has a few DRM free games, hasn't it?

Resolves #3950

### CODE REVIEW

**Comment by strycore** [comment]
I can't even....

**Comment by danieljohnson2** [comment]
Now, now. You could even explain. This is not an unreasonable change.

**Comment by strycore** [comment]
I think there is some confusion with the naming of this attribute. drm_free is supposed to separate services that provide games without the need of an additional launcher. They install games in a directory which can be relocated. This is not the case for Steam games or games from any other launcher.

Removing this drm_free attribute does not solve what the original ticket was asking for, which was to re-import previously installed lutris games.

If you think there is a name better suited for that attribute then I'm all open for it. But right now, the Humble and GOG services work differently from other services, this is why this attribute is present.

**Comment by danieljohnson2** [comment]
I see; the seems related to the idea that each service game is related 1-to-1 with a Lutris PGA game. Just picking some random install via "locate" would be broken in some way, I suppose?

**Comment by strycore** [comment]
the whole purpose of services is to have a way to install and launch games without the need of having install scripts on the website. For every other service, we can detect games that are installed and available. We do this for Steam and EGS. 
in this case 'drm_free' means that Lutris is in charge of managing the game files, where it's not the case for other services.

**Pull request closed without merging**
