### PR TITLE
Improve formatting in the Wine dialog and add a missing dot.

### PR DESCRIPTION
**Pull request by tannisroot**
Before:
screenshot from 2018-10-05 12-12-56
After:
screenshot from 2018-10-05 12-12-37

### CODE REVIEW

**Comment by RobLoach** [comment]
Unsure the newline is needed, since it's building on the same idea as the previous sentence.

**Comment by tannisroot** [comment]
You mean like this? I mean, it looks fine but I feel like it's a bit of a waste of space.
image

**Comment by strycore** [comment]
I actually like the last one better!

**Comment by tannisroot** [comment]
Ok, I made it look like the last screenshot.

**Comment by strycore** [comment]
Nice!

**Pull request merged**
