### PR TITLE
Fix installers.rst formatting issue

### PR DESCRIPTION
**Pull request by canepan**
Also, make code block formatting more uniform

### CODE REVIEW

**Comment by danieljohnson2** [comment]
I'm lost. This commit re-arranges double-colons '::'; but I can't find a lick of documentation on what the heck '::' means and where it should go. Can you enlighten me?

**Comment by canepan** [comment]
"::" in RestructiredText means the following spaced lines are a code block.
I figured it from the rest of the doc

⁣Nicola Canepa​

Il giorno 12 feb 2023, 10:13, alle ore 10:13, Daniel Johnson ***@***.***> ha scritto:

**Comment by canepan** [comment]
Some example using `::` can be found [here](https://github.com/ralsina/rst-cheatsheet/blob/master/rst-cheatsheet.rst#blocks) or [here](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#literal-blocks).

**Comment by danieljohnson2** [comment]
This is a weird format. Thank you for the documentation. It seems to endorse both forms, though.

So why is it better to have this with the '::' merged into the preceding ':'?

**Comment by canepan** [comment]
I am a fan of uniformity, and both the main README file and (roughly) 20 out of 32 instances in the same file are using this format.  
Besides that, I prefer it :).

The main reason for this change was to fix a broken formatting at line `213`:

image

but then I got carried away

**Comment by danieljohnson2** [comment]
Ah, I see what I mean. That's broken. I'll merge the PR to fix that.

**Pull request merged**
