### PR TITLE
Fix issue #2385

### PR DESCRIPTION
**Pull request by skriptmonkey**
Fixes issue #2385 
Higan, MelonDS, Redream, and TIC-80 are no longer available to download and install via https://lutris.net/runners. Also, their functionality looks to already exist within the Libretro runner.

### CODE REVIEW

**Comment by telanus** [comment]
Higan Yes, It can be replaced with Libretro's bsnes core. Byuu actively help to keep the core inline with the stand-alone emu.

melonDS: The Current Libretro Core is quite a bit out of sync with the stand-alone emu. 

Redream: The Libretro core is ages behind the stand-alnoe emu, and will never be able to get on par with what the stand-alone. and after the drama the dev had with libretro, it went close source. I will try and get permission of the dev to host stable releases, but doubt it'll happen.

 TIC-80: The Libretro core isn't as usable as the stand-alone. The way Libretro implement their retropad isn't conducive to  TIC-80's usability

**Comment by soredake** [comment]
Redream can be replaced with flycast https://github.com/libretro/flycast/

**Comment by skriptmonkey** [comment]
@telanus Understood, but these runners were already unavailable via the website/server. All I'm doing is syncing the client to the servers by removing the entries from showing up in Manage Runners. Otherwise users will expect the stand-alone functionality and try to install, only to be greeted by a 404.

@soredake Thank you. Flycast is one of the cores included in the Libretro runner that is currently present in Lutris. :)

**Comment by telanus** [comment]
> I think it would be better to instead just comment out those runners until we add actually build them and start distributing.
For redream, one need to use official files, as the emu is closed-source

**Comment by strycore** [comment]
I agree that those runner should not have been displayed. Please submit build scripts in the buildbot repo so we can distributing those emulators and have runners for them.

**Pull request merged**
