### PR TITLE
Implement fsync toggle

### PR DESCRIPTION
**Pull request by openglfreak**
Mostly a copy&paste of the esync option.

Supersedes #2869

### CODE REVIEW

**Comment by openglfreak** [comment]
Why are some merged commits listed???
I'll try rebasing onto master

**Comment by openglfreak** [comment]
That worked.

**Comment by robzombie91** [comment]
Will this option be disabled like gamemode if fsync is not detected in the current wine build or will it just throw an error if its not detected during startup?

**Comment by openglfreak** [comment]
@robzombie91 It will be disabled if fsync is not detected in the Wine version.

**Pull request merged**
