### PR TITLE
Update and rename lutris.pot to it.po

### PR DESCRIPTION
**Pull request by albanobattistella**
IT translation.

### CODE REVIEW

**Comment by strycore** [comment]
Well I guess that works since I wanted to get rid of the lutris.pot file.

**Comment by albanobattistella** [comment]
Hi mathieu,

the italian translation don't work.
Please, can you check?
if you need help let me know!
thanks.

regards,

Albano

________________________________
Da: Mathieu Comandon <notifications@github.com>
Inviato: mercoledì 27 marzo 2019 04:12
A: lutris/lutris
Cc: albanobattistella; Author
Oggetto: Re: [lutris/lutris] Update and rename lutris.pot to it.po (#1921)


Well I guess that works since I wanted to get rid of the lutris.pot file.

**Comment by strycore** [comment]
Hey @albanobattistella 
Please see this issue: https://github.com/lutris/lutris/issues/728
This is something we have yet to get implemented.

**Comment by albanobattistella** [comment]
thanks!

________________________________
Da: Mathieu Comandon <notifications@github.com>
Inviato: sabato 22 giugno 2019 20:33
A: lutris/lutris
Cc: albanobattistella; Mention
Oggetto: Re: [lutris/lutris] Update and rename lutris.pot to it.po (#1921)


Hey @albanobattistella<https://github.com/albanobattistella>
Please see this issue: #728<https://github.com/lutris/lutris/issues/728>
This is something we have yet to get implemented.

**Pull request merged**
