### PR TITLE
DuckStation as a runner.

### PR DESCRIPTION
**Pull request by mintymoons**
- Addition of DuckStation as a runner.

### CODE REVIEW

**Comment by danieljohnson2** [comment]
I see this code places the downloaded BIOS files in ~/.local/share/duckstation/..., not inside ~/.local/share/lutris anywhere. Why is that?

**Comment by mintymoons** [comment]
Greetings, @danieljohnson2.

Because DuckStation detects BIOS files in this directory when it is opened by the first time: ~/.local/share/duckstation/.
Nonetheless, end users can change it in the mentioned emulator.

**Comment by danieljohnson2** [comment]
Careful there; those changes to the Atari 800 and MicroM8 runners maybe should be separate from this PR; you can do that by using separate branches for unrelated changes and submitting more than one PR.

**Comment by mintymoons** [comment]
I haven't submitted this PR yet. it appeared automatically before creating it.
Could you close this PR, please?

**Comment by danieljohnson2** [comment]
Yes, but can't you do that? And this is the DuckStation PR; I thought you wanted this in.

**Comment by mintymoons** [comment]
I only submitted this PR about DuckStation.

Atari800 and MicroM8's links will be in another PR with a new branch.

**Comment by danieljohnson2** [comment]
I think what you should do is reset the DuckStation branch back to commit 50b86d74eecb0716bb8a2eb3b065a677113c2cf2, which is the original DuckStation commit, and then force-push that to fix this PR.

Then do a new branch off master and do the other stuff that way.

**Comment by mintymoons** [comment]
I did this and created a new branch for the new links. Could you check it again, please?

**Comment by danieljohnson2** [comment]
That revert has put it back where it was.

**Comment by mintymoons** [comment]
It is a relief. Thanks for your revision.

**Comment by strycore** [comment]
I torn about the inclusion of PS1 bios file URLs. 
We've traditionally avoided doing that, with some exceptions, like Atari800. 
But put this into consideration: Atari800 support the XE130 released in 1983. Lutris added support for Atari800 around 2010. So it was 27 years later. We're in 2024 and the PS1 was released in 1995, so 29 years ago. 
Based on that, we should consider shipping links to BIOS files from a machine that is almost 30 years old.

**Comment by mintymoons** [comment]
Greetings, @strycore.

Thank you for your feedback. I really appreciate it.

**Comment by mintymoons** [comment]
@strycore. BIOS files URLs were removed.

**Comment by strycore** [comment]
> @strycore. BIOS files URLs were removed.

Thanks, I think we should come up with a more generic solution for dealing with BIOS files. One that's not specific for Duckstation. The same BIOS files would be needed for the PSX Retroarch cores. And we need a way to handle BIOS files on a more generic level for other types of platforms (Amiga, Dreamcast, PS2, ....)

**Comment by mintymoons** [comment]
It was a pleasure, @strycore.

**Comment by mintymoons** [comment]
Could I create a new discussion to write about how we should handle BIOS generically for many emulators? It is to refer to emulators in general instead of DuckStation or this PR.

I tried that before and I found some ways. I also want to learn about this.

**Comment by strycore** [comment]
Yes, you totally can!

**Comment by mintymoons** [comment]
It is appreciated. I will create the new discussion.

**Comment by mintymoons** [comment]
Do you recommend me to categorise the new discussion as "General" or "Q&A"? I try to be precise about it.

**Comment by strycore** [comment]
General is fine

**Comment by strycore** [comment]
Merging this before releasing 0.5.18

**Pull request merged**
