### PR TITLE
Partial adding types to utils folder

### PR DESCRIPTION
**Pull request by qarmin**
Should decrease mypy errors by ~200/300

I found some possibly invalid types and I marked this with `TODO MYPY` so this needs to be fixed in different PR

### CODE REVIEW

**Comment by danieljohnson2** [comment]
@strycore is not fond of all the ``Optional[str]`` stuff, so I turned on implicit_optional so we can do optional parameters without it; ``p: str = None`` is understood as ``p: Optional[str] = None``.

I see you've put accurate types on all the parameters like that, which is more correct in a way, but noisier.

**Comment by qarmin** [comment]
I started adding them out of habit.

I'm not sure, but adding them rather allowed more errors to be displayed in mypy(but it is also possible that adding the types to all the parameters allowed mypy to find them better)

I may change them back to var: type = None, but this seems less readable to me than the current solution

**Comment by strycore** [comment]
It's fine to have some Optional stuff. Maybe if we have too many of them, it's a sign we should write better, more deterministic code.

**Comment by strycore** [comment]
damn, I was about to merge this and there are so many conflicts

**Pull request closed without merging**
