### PR TITLE
Fix error formating in case of missing dependency

### PR DESCRIPTION
**Pull request by sigmaSd**
Fix https://github.com/lutris/lutris/issues/913

### CODE REVIEW

**Comment by strycore** [comment]
That just avoids a crash but does not fix the root issue, which is that the dependency is missing.

**Comment by sigmaSd** [comment]
No did you check the image I upload it? it still crashes that's not the point of this patch, the problem it fixes is if you have a missing required binaries the error message have the right format for example without this patch, I got 'requires b or s or d oa or r' instead of 'requires bsdtar' when it's missing.

**Comment by sigmaSd** [comment]
here is the picture I didnt know that github can handle image..
screenshot from 2018-06-12 08-19-58

**Comment by strycore** [comment]
I think I misread what the fix was :sweat_smile:

**Comment by sigmaSd** [comment]
Sorry for the bad title thats what mislead you probably xD

**Pull request merged**
