### PR TITLE
Do not grab focus when redrawing the main view.

### PR DESCRIPTION
**Pull request by danieljohnson2**
Changing focus here causes the view-adjust-menu to close whenever
the zoom_adjustment slider is changed.

Also, it interferes with arrow-key navigation between sidebar items.

Resolves lutris/lutris#3794

### CODE REVIEW

**Comment by strycore** [comment]
Please revert your changes to docs/installers.rst. Do not document possible bugs.

**Review by strycore — CHANGES_REQUESTED** [review]
I don't understand the changes made to the documentation. Please revert them.

**Comment by danieljohnson2** [comment]
I did not change that file; I don't understand how the conflict happened. I'll try to revert them.

**Comment by danieljohnson2** [comment]
BTW, it appears to me that the reverted changes were spelling corrections.

**Comment by strycore** [comment]
Those may have been old data from the documentation present when you made the branch

**Review by strycore — APPROVED** [review]

**Comment by danieljohnson2** [comment]
My faith in the magic power of git is shaken.

**Comment by strycore** [comment]
Some commits got force pushed in the middle of this PR, weird but not a big issue.

**Pull request merged**
