### PR TITLE
Fix regression found by @telanus

### LINKED ISSUE #750: Error while completing task
error after updating this morning:

ERROR    2018-02-04 08:36:44,365 [jobs]:Error while completing task <bound method LutrisWindow.sync_icons of <lutriswindow.LutrisWindow object at 0x7ff3f32d7b88 (LutrisWindow at 0x31c8280)>>: name 're' is not defined
<class 'NameError'> name 're' is not defined
  File "/src/lutris/lutris/util/jobs.py", line 29, in target
    result = self.function(*args, **kwargs)
  File "/src/lutris/lutris/gui/lutriswindow.py", line 392, in sync_icons
    callback=self.on_image_downloaded)
  File "/src/lutris/lutris/util/resources.py", line 40, in fetch_icons
    results = api.get_games(game_slugs=missing_media_slugs)
  File "/src/lutris/lutris/api.py", line 97, in get_games
    page_match = re.search(r'page=(\d+)', response_data['next'])

### PR DESCRIPTION
**Pull request by Xenega**
See #750

### CODE REVIEW

**Comment by telanus** [comment]
with this done I still get the following:

Error while completing task <bound method LutrisWindow.sync_icons of <lutriswindow.LutrisWindow object at 0x7fa305e05af8 (LutrisWindow at 0x1f1a280)>>: name 'missing_media_slugs' is not defined
<class 'NameError'> name 'missing_media_slugs' is not defined
  File "~/src/lutris/lutris/util/jobs.py", line 29, in target
    result = self.function(*args, **kwargs)
  File "~/src/lutris/lutris/gui/lutriswindow.py", line 392, in sync_icons
    callback=self.on_image_downloaded)
  File "~/src/lutris/lutris/util/resources.py", line 42, in fetch_icons
    results = api.get_games(game_slugs=missing_media_slugs)
  File "~/src/lutris/lutris/api.py", line 104, in get_games
    page_result = get_games(game_slugs=missing_media_slugs, page=page)

**Comment by telanus** [comment]
Thanx, seem to fix the errors I got

**Comment by telanus** [comment]
Not sure if it is this "update/fix", I used it as a template to fix my local copy. But since I did it yesterday, Lutris's memory footprint shot up from about 500mb to almost 2gb. Maybe @strycore might have an idea why

**Comment by Xenega** [comment]
What is strange is you should not download icons if they already exists. I added a debug log, can you check how many icons lutris sync every day ?

**Comment by telanus** [comment]
@Xenega It doesn't print anything :(. 

The last few days when Lutris was running it's memory usage was about 150-160MB (or so says the system monitor), but with the fixes in the memory usage skyrocketed to almost 2GB, today I terminated Lutris when it reached 1GB (of memory used). Currently it sits at a low 130mb.

**Comment by strycore** [comment]
thanks!

**Comment by Xenega** [comment]
@telanus 
For your problem of memory, open a issue.

**Pull request merged**
