### PR TITLE
Do not hide the runner configure button

### LINKED ISSUE #3926: Runners can be configured when not yet installed, but not after removal
### Bug description

When you go into the Preferences dialog, Runners section, all the runners may be configured even if not installed. But  if you remove one, it's configure button disappears.

### How to Reproduce

Go into Preferences, select "Runners". Now, pick a runner and remove it. The configure button for that runner will disappear.

I think that is correct- but notice that all the other uninstalled runners have configure buttons. See the media attached. That can't be right.

### Expected behavior

I expect that the configure button will appear only for installed runners in the first place.

### Log output

```shell
INFO     2021-12-24 07:12:16,550 [startup.check_driver:53]:Using NVIDIA drivers 470.86 for x86_64
INFO     2021-12-24 07:12:16,550 [startup.check_driver:57]:GPU: NVIDIA GeForce RTX 3060
INFO     2021-12-24 07:12:16,550 [startup.check_driver:73]:GPU: 10DE:2503 196E:1377 (nvidia drivers)
DEBUG    2021-12-24 07:12:16,725 [lutriswindow.update_store:451]:Showing 25 games
DEBUG    2021-12-24 07:12:20,443 [application.show_window:259]:Showing window <class 'lutris.gui.config.preferences_dialog.PreferencesDialog'>{}
DEBUG    2021-12-24 07:12:26,667 [application.on_app_window_destroyed:276]:Removed window <class 'lutris.gui.config.preferences_dialog.PreferencesDialog'>{}
INFO     2021-12-24 07:12:28,505 [application.do_shutdown:631]:Shutting down Lutris

Hmm, using the master branch to repro produces less logging!
```

### System Information

```shell
[System]
OS:              Pop!_OS 21.10 impish
Arch:            x86_64
Kernel:          5.15.8-76051508-generic
Desktop:         GNOME
Display Server:  x11

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 7 5800X 8-Core Processor
Physical cores:  8
Logical cores:   16

[Memory]
RAM:             31.4 GB
Swap:            0.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 470.86
OpenGL Core:     4.6.0 NVIDIA 470.86
OpenGL ES:       OpenGL ES 3.2 NVIDIA 470.86
Vulkan:          Supported
```

### Media (optional)

Screenshot from 2021-12-24 07-06-15

### Checklist:

- [X] I'm not asking for support with a game or the wine runner.
- [X] I have followed the above mentioned guides and have all the graphics and wine dependencies installed.
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

### PR DESCRIPTION
**Pull request by danieljohnson2**
If we always want it, remove the runner shouldn't hide it.

This PR is an alternative to #3927; you won't want both.

Resolves #3926

### CODE REVIEW

**Comment by danieljohnson2** [comment]
I'm quite surprised you installed both PRs (this and #3927) for this issue; they are rather in conflict.

**Comment by strycore** [comment]
If you make PRs a "choose your own adventure" game, this is another level I'm not prepared for!

1 PR per issue please!

**Comment by danieljohnson2** [comment]
Okay. I can close old PRs to direct you to the one I prefer; I have already done this for outright broken PRs.

**Comment by strycore** [comment]
if anything is closed by another PR then yes, close the other one. But really, you shouldn't be developing 2 implementations, it seems much more productive to agree on a design beforehand. Are you on Discord by any chance? You should be in the dev channel.

**Comment by danieljohnson2** [comment]
I looked into the Discord and found it to be chaos. I can look again if you like. 'dev' channel you say?

The double PRs happen when someone argues persuasively enough that my first PR is wrong; I was leaving you two so you could pick when convenient for you. I don't set out to write two.

You seemed to be busy with the website, and I did not want to interrupt you all the time.

**Comment by strycore** [comment]
The Discord is indeed chaos, but it's to be expected for something that large. The dev channel is private and very low activity. Ping me or Tannis on Discord to get access.

I've caught up with the website so I can dedicate time on the client now.

**Comment by danieljohnson2** [comment]
I see; I will do that, but not now. Getting to be late for the day job.

**Comment by strycore** [comment]
And I should get to sleep instead of reviewing tickets!

**Pull request merged**
