### PR TITLE
WIP: Start logging play sessions to prepare for "Time Played Calendar"

### PR DESCRIPTION
**Pull request by FalkF**
Hi :wave: 
In order to be able to present some data when #2256 gets implemented we should start logging the playtime per session.

### CODE REVIEW

**Comment by FalkF** [comment]
It would be cool to get some kind of response on this ;)
I really would love to work on this some more.

**Comment by strycore** [comment]
The start of the PR looks good. At some point, I'd like to have a way to sync the playtimes to the website, but that can maybe be integrated at a later stage.

**Comment by FalkF** [comment]
Nice, the website would be the perfect place for a cool looking graph. I might take a look at the backend work after this PR.

But first would be good to add `average_playtime`, `longest_session` and `consecutive_days_played` to `games` in the pga. Displaying these values on the `game_panel` must suffice for now since I am not experienced enough in python for any fancy graphs :D

Is there anything else needed to get this merged?

**Comment by FalkF** [comment]
So this is what I've got so far:
lutris_stats_feature

Might be a bit much, any opinions? I will test some more and then remove the WIP soon.

**Comment by strycore** [comment]
Yes, this is good for testing but there is no need to display those metrics here. Maybe when clicking on the total playtime or a link next to it could expand the details.

**Comment by strycore** [comment]
PR considered abandoned.

**Pull request closed without merging**
