### PR TITLE
Deleting an unnecessary line

### PR DESCRIPTION
**Pull request by LeandroStanger**

### CODE REVIEW

**Comment by LeandroStanger** [comment]
@cho2 You could translate appdata and desktop to Indonesian?

**Comment by cho2** [comment]
@LeandroStanger
 https://github.com/lutris/lutris/blob/master/share/appdata/lutris.appdata.xml and https://github.com/lutris/lutris/blob/master/share/applications/lutris.desktop ?

**Comment by LeandroStanger** [comment]
@cho2 Yes

**Comment by Tom-Todd** [comment]
The line you removed should now end with a />

**Pull request merged**
