### PR TITLE
Allow user to set cache directory in settings and also delete existing cache files

### LINKED ISSUE #3695: Allow user to set cache directory in settings and change the language around it
I have just found myself in the rather unpleasant situation of having my /home partition completely full due to Lutris saving the installer file in /home/user/.cache/lutris. This led to the installation process failing and to me having to download 30+ GB of files _again_.
Now, there is indeed a "cache" option, but it is rather difficult to understand what it does if one doesn't click on it and read the text, which is rather poor UX. I only found it out _after_ the download failed, as it was _not_ clear from the language that this would be the place where the downloaded files would be saved. I also noticed that that option is nowhere to be fond in the general "settings" page, so one can't set it as a general rule.
I would therefore suggest moving the option there or at least making it available there as a general, application-wide option that can be then overridden with the button in the installation phase. I would also suggest renaming the feature from "cache", which has little meaning to most users in this context, to "set installer download path", "save installer to" or similar verbiage, so that the feature is clearer in its scope and definition.

### PR DESCRIPTION
**Pull request by pcoder59**
Adds the ability to set cache folder, i.e. installer download location globally in global settings.

Also added a button that on click will delete all the cached installer files.

Closes #3695

### CODE REVIEW

**Comment by strycore** [comment]
The system options is not the place for this setting.
A purge cache option isn't desired.

**Comment by pcoder59** [comment]
> The system options is not the place for this setting. A purge cache option isn't desired.

Why not close the related issue then? What exactly does the issue demand?

**Comment by strycore** [comment]
We're going to add a section in the preferences windows to set paths. We need to make the cache path more visible. 

The feature is wanted, it's just that I don't want a button that potentially erases hundreds of GB of data so easily accessible. Especially now that we have a button to open folder locations in the file browser. It's just as easy to click the browse button, selecting all and pressing delete.

**Comment by strycore** [comment]
If you want to take a shot at it, you can take a look at how UpdatesBox and AccountsBox are implemented. Those are 2 recent additions to the preferences window.

**Pull request closed without merging**
