### PR TITLE
Add a switch for "Remove from library" in preferences

### PR DESCRIPTION
**Pull request by OlegAckbar**
Removing game from the library will erase playtime and "last start" time

### CODE REVIEW

**Comment by strycore** [comment]
We're obviously all disagreeing on that matter.

Initially, Lutris would keep uninstalled games in the library.
Then we implemented library sync.
Then @danieljohnson2 switched the default to keep games when library sync is enabled
Then I realized that I was changing that default setting almost every time I wanted to remove a game. So I made it enabled by default.
And now we're back to square one, with not deleting games by default.

Technically, we have 1 solution left to try out, which would be to remove games when library sync is enabled. But I don't think this makes a lot of sense.

**Comment by danieljohnson2** [comment]
There are so many options here!

I say: start the check-boxes in the [-] indeterminate state, and then if left that way, we flip a coin to decide. That covers everybody's desires! Well, sometimes anyway,

**Comment by OlegAckbar** [comment]
What about a checkbox in Lutris settings which will decide default behavior?

**Comment by danieljohnson2** [comment]
Can *that* checkbox start of as [-] and flip a coin?

**Comment by strycore** [comment]
> What about a checkbox in Lutris settings which will decide default behavior?

Ah, you're one of those people who want to add one gazillion checkboxes to the Lutris preferences to make it the most bloated piece of software on earth. 
Unfortunately, we don't have the kind of workforce to even attempt aiming to be in the Guiness Book of World Records.
I'm not sure it's a viable strategy.

**Comment by OlegAckbar** [comment]
I've added a switch that will control default state of "Remove from library". It's on by default

**Comment by strycore** [comment]
Sorry, we've run out of space to add another checkbox so we can't take that patch

**Comment by strycore** [comment]
Let's say that my motivation for switching the default to True was partly motivated by the fact that I was working on library sync and removal was wanted 100% of the time. Now that library sync is implemented, this would no longer be the case but the change to true was also partly motivated by the installation of games for testing only which is also not the typical use case when you're not a Lutris developer. 

The change that @danieljohnson2 made previously kept the game only if sync was activated. That means people without sync enabled lose their play times by default.

If we default to False like suggested in the PR, games are kept by default and we go back to having to remove a game twice to remove it completely.

Having a toggle in the preferences would be understood by no one. This is not something we will consider. 

Let's eliminate True as the default because that doesn't satisfy the typical use case. If we use False instead of not Library sync enabled, then we treat every user as if they had sync enabled. And it's a safer option too, there's no undelete for games while having the game a second time isn't the end of the world.

I've now switch the default to False

**Comment by danieljohnson2** [comment]
Well, that's simple. Remove twice by default makes sense to me if you *are* using library sync, which we are encouraging firmly. So I guess it's okay.

**Pull request closed without merging**
