### PR TITLE
use ldconfig for gamemodepath and use  $LIB for gamemode

### PR DESCRIPTION
**Pull request by sigmaSd**
$LIB looks to be working just if anyone has a problem check that you have lib32 build of gamemode

### CODE REVIEW

**Comment by sigmaSd** [comment]
fix https://github.com/lutris/lutris/issues/1322 https://github.com/lutris/lutris/issues/1304

**Comment by sigmaSd** [comment]
We probably need  the wiki to mention gamemode, it seems like most ppl don't install the 32bit build

**Comment by sigmaSd** [comment]
Right now it's not a hard requirement as long one of feral lib exists on the system gamemode will be available, just wanted to mention it on the wiki so ppl become aware

**Comment by Zeioth** [comment]
Added to the wiki:
https://github.com/lutris/lutris/wiki/Performance-Tweaks#enable-game-mode

**Comment by strycore** [comment]
Please rebase your PR against the `next`  branch

**Comment by sigmaSd** [comment]
Thanks for the wiki entry!

**Comment by sigmaSd** [comment]
rebased

**Pull request closed without merging**
