### PR TITLE
update dxvk_versions at the first acess of config dialog once per lutris instance

### PR DESCRIPTION
**Pull request by sigmaSd**
fix https://github.com/lutris/lutris/issues/1287

### CODE REVIEW

**Comment by tannisroot** [comment]
What does “once” here mean?

**Comment by sigmaSd** [comment]
was lazy to write :p i meant what strycore said

> I agree, it could be reloaded once per lutris instance, when the config dialog is first accessed

**Comment by sigmaSd** [comment]
I would've preferred it just to update each time lutris open ( means less code) but I thought maybe strycore has reasons for wanting it to update at config dialog access

**Comment by sigmaSd** [comment]
as @PythonicChemist suggested here are  two alternative solutions 

https://pastebin.com/jRBayyzK 
or
```python 
@functools.lru_cache(maxsize=None, typed=False) 
def init_dxvk_versions():
```
so wanted to know what do u prefer @strycore ?

**Comment by strycore** [comment]
The approach can be changed after the release

**Comment by strycore** [comment]
Also, I like the decorator approach more, with proper naming it's easier to see what the purpose is

**Pull request merged**
